### ISSUE TITLE
Rikolti `validate_by_mapper_type` dag is in a success state, but doesn't produce any validation reports

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#1148]
Rikolti validate_by_mapper_type dag is in a success state, but doesn't produce any validation reports. Instead it says to: `INFO - please validate manually: [11068, 26723, 27968]`

Also checked the rikolti-data bucket:
- https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#11068/
- https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26723/
- https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27968/
They include the vernacular and mapped metadata, but not the validation reports.

The four below were run:

`"rikolti_mapper_type":"oai.content_dm.csu_sac"`
run id: manual__2024-10-31T18:19:15+00:00
link to airflow: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2024-10-31T18%3A19%3A15%2B00%3A00&tab=logs&task_id=validate_endpoint

`"rikolti_mapper_type":"oai.content_dm.chico"`
run id: manual__2024-10-31T15:59:56+00:00
link to airflow: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2024-10-31T15%3A59%3A56%2B00%3A00&tab=details

`"rikolti_mapper_type":"marc.ucb_tind"` - limit: 1
run id: manual__2024-10-31T18:58:57+00:00
link to airflow: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2024-10-31T18%3A58%3A57%2B00%3A00&tab=details

`"rikolti_mapper_type":"oai.content_dm.csudh"` - limit: 1
run id: manual__2024-10-31T18:59:27+00:00
link to airflow: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2024-10-31T18%3A59%3A27%2B00%3A00&tab=details

Here's the log from `oai.content_dm.csu_sac`'s `validate_endpoint` task:
```
[2024-10-31, 18:31:17 UTC] {logging_mixin.py:188} INFO - >>> Validating 3/3 collections described at https://registry.cdlib.org/api/v1/rikoltifetcher/?format=json&rikolti_mapper_type=oai.content_dm.csu_sac&ready_for_publication=true
[2024-10-31, 18:31:17 UTC] {logging_mixin.py:188} INFO - 11068  Validating collection
[2024-10-31, 18:31:18 UTC] {logging_mixin.py:188} WARNING - 11068 : Invalid URL 'False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="11068"&field=isShownAt&limit=100000': No scheme supplied. Perhaps you meant [https://False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="11068"&field=isShownAt&limit=100000?](https://false/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%2211068%22&field=isShownAt&limit=100000?)
[2024-10-31, 18:31:18 UTC] {logging_mixin.py:188} INFO - 26723  Validating collection
[2024-10-31, 18:31:18 UTC] {logging_mixin.py:188} WARNING - 26723 : Invalid URL 'False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="26723"&field=isShownAt&limit=100000': No scheme supplied. Perhaps you meant [https://False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="26723"&field=isShownAt&limit=100000?](https://false/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%2226723%22&field=isShownAt&limit=100000?)
[2024-10-31, 18:31:18 UTC] {logging_mixin.py:188} INFO - 27968  Validating collection
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING - 27968 : Invalid URL 'False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="27968"&field=isShownAt&limit=100000': No scheme supplied. Perhaps you meant [https://False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="27968"&field=isShownAt&limit=100000?](https://false/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%2227968%22&field=isShownAt&limit=100000?)
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING - ------------------------------------------------------------
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING - -------------------- Validation Errors ---------------------
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING - ------------------------------------------------------------
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -  Collection 11068: Invalid URL 'False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="11068"&field=isShownAt&limit=100000': No scheme supplied. Perhaps you meant [https://False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="11068"&field=isShownAt&limit=100000?](https://false/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%2211068%22&field=isShownAt&limit=100000?) 
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/map_registry_collections.py", line 120, in validate_endpoint
    num_rows, version_page = create_collection_validation_csv(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 218, in create_collection_validation_csv
    result = validate_collection(collection_id, mapped_page_paths, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 66, in validate_collection
    rikolti_ids, new_ids = validate_page(collection_id, page_path, validator)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 183, in validate_page
    get_comparison_data(collection_id,
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 229, in get_comparison_data
    couch_data = get_couch_db_data(collection_id, harvest_ids)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 332, in get_couch_db_data
    couch_data = couch_db_request(collection_id, field_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 298, in couch_db_request
    response = requests.get(url, verify=False, timeout=settings.COUCH_TIMEOUT)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING - requests.exceptions.MissingSchema: Invalid URL 'False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="11068"&field=isShownAt&limit=100000': No scheme supplied. Perhaps you meant [https://False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="11068"&field=isShownAt&limit=100000?](https://false/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%2211068%22&field=isShownAt&limit=100000?)
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING - <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -  Collection 26723: Invalid URL 'False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="26723"&field=isShownAt&limit=100000': No scheme supplied. Perhaps you meant [https://False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="26723"&field=isShownAt&limit=100000?](https://false/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%2226723%22&field=isShownAt&limit=100000?) 
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/map_registry_collections.py", line 120, in validate_endpoint
    num_rows, version_page = create_collection_validation_csv(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 218, in create_collection_validation_csv
    result = validate_collection(collection_id, mapped_page_paths, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 66, in validate_collection
    rikolti_ids, new_ids = validate_page(collection_id, page_path, validator)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 183, in validate_page
    get_comparison_data(collection_id,
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 229, in get_comparison_data
    couch_data = get_couch_db_data(collection_id, harvest_ids)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 332, in get_couch_db_data
    couch_data = couch_db_request(collection_id, field_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 298, in couch_db_request
    response = requests.get(url, verify=False, timeout=settings.COUCH_TIMEOUT)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING - requests.exceptions.MissingSchema: Invalid URL 'False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="26723"&field=isShownAt&limit=100000': No scheme supplied. Perhaps you meant [https://False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="26723"&field=isShownAt&limit=100000?](https://false/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%2226723%22&field=isShownAt&limit=100000?)
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING - <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -  Collection 27968: Invalid URL 'False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="27968"&field=isShownAt&limit=100000': No scheme supplied. Perhaps you meant [https://False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="27968"&field=isShownAt&limit=100000?](https://false/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%2227968%22&field=isShownAt&limit=100000?) 
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING - Traceback (most recent call last):
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/map_registry_collections.py", line 120, in validate_endpoint
    num_rows, version_page = create_collection_validation_csv(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 218, in create_collection_validation_csv
    result = validate_collection(collection_id, mapped_page_paths, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 66, in validate_collection
    rikolti_ids, new_ids = validate_page(collection_id, page_path, validator)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 183, in validate_page
    get_comparison_data(collection_id,
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 229, in get_comparison_data
    couch_data = get_couch_db_data(collection_id, harvest_ids)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 332, in get_couch_db_data
    couch_data = couch_db_request(collection_id, field_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 298, in couch_db_request
    response = requests.get(url, verify=False, timeout=settings.COUCH_TIMEOUT)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING -   File "/usr/local/airflow/.local/lib/python3.11/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING - requests.exceptions.MissingSchema: Invalid URL 'False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="27968"&field=isShownAt&limit=100000': No scheme supplied. Perhaps you meant [https://False/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key="27968"&field=isShownAt&limit=100000?](https://false/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%2227968%22&field=isShownAt&limit=100000?)
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} WARNING - <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} INFO - ************************************************************
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} INFO - 3 collections encountered validation errors
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} INFO - please validate manually: [11068, 26723, 27968]
[2024-10-31, 18:31:19 UTC] {logging_mixin.py:188} INFO - ************************************************************
```

**Comment by christinklez** [comment]
- We don't want to turn Couch on; and we don't want to validate against Couch
   - This would mean we can't validate isShownBy & isShownAt
- To do: remove the Couch url's from MWAA
- During data validation, we can spot check the URLs to make sure they have valid thumbnail URLs
