### ISSUE TITLE
TIND `validate_by_mapper`'s throws 503 errors when fetching batch jobs; possibly does not like being hit in quick succession (running individual collections works fine) - implement retries globally for the fetcher

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#1150]
**Description:** For the TIND mapper, every few collection fetches errors out. The very end of the log has this error: `AttributeError: 'dict' object has no attribute 'version'`

**Run ID:** manual__2024-11-05T00:19:36+00:00
**Airflow link:** https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2024-11-05T00%3A19%3A36%2B00%3A00&tab=details&base_date=2024-11-05T00%3A19%3A36%2B00%3A00

**`fetch_endpoint` log:**
```
[2024-11-05, 00:19:55 UTC] {logging_mixin.py:188} INFO - >>> Fetching 67/67 collections described at https://registry.cdlib.org/api/v1/rikoltifetcher/?format=json&rikolti_mapper_type=marc.ucb_tind&ready_for_publication=true
[2024-11-05, 00:22:29 UTC] {logging_mixin.py:188} INFO - 150   : success,    37 pages,   3652 items,   3544 solr items,   108 new items, solr count last updated: December 02, 2022 15:06:59.638955
[2024-11-05, 00:22:30 UTC] {logging_mixin.py:188} INFO - 747   : success,     1 pages,      2 items,      2 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:59.248984
[2024-11-05, 00:22:31 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 1454: [1454]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Florence_Merriam_Bailey_Papers_1887_1940'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Florence_Merriam_Bailey_Papers_1887_1940%27})
[2024-11-05, 00:22:32 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 2515: [2515]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=therese_bonney'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=therese_bonney%27})
[2024-11-05, 00:22:33 UTC] {logging_mixin.py:188} INFO - 3461  : success,     1 pages,      1 items,      1 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:56.829846
[2024-11-05, 00:22:33 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 3928: [3928]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Cassidy_Family_Papers'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Cassidy_Family_Papers%27})
[2024-11-05, 00:22:34 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 4442: [4442]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=City_Lights_Books_Records_OAI'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=City_Lights_Books_Records_OAI%27})
[2024-11-05, 00:22:35 UTC] {logging_mixin.py:188} INFO - 5058  : success,     1 pages,      1 items,      1 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:55.214195
[2024-11-05, 00:22:36 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 5636: [5636]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=georgedavidson_oai'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=georgedavidson_oai%27})
[2024-11-05, 00:22:36 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 6083: [6083]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=disabledStudentsProgramRecords'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=disabledStudentsProgramRecords%27})
[2024-11-05, 00:22:38 UTC] {logging_mixin.py:188} INFO - 6200  : success,     1 pages,     20 items,     19 solr items,     1 new items, solr count last updated: December 02, 2022 15:06:53.907259
[2024-11-05, 00:22:40 UTC] {logging_mixin.py:188} INFO - 7497  : success,     1 pages,      1 items,      1 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:53.133473
[2024-11-05, 00:22:40 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 7875: [7875]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=fww1p'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=fww1p%27})
[2024-11-05, 00:22:41 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 8776: [8776]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Governors_Commission_on_the_Los_Angeles_Riots_Records_OAI'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Governors_Commission_on_the_Los_Angeles_Riots_Records_OAI%27})
[2024-11-05, 00:22:43 UTC] {logging_mixin.py:188} INFO - 8980  : success,     1 pages,      8 items,      8 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:52.063134
[2024-11-05, 00:22:43 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 9673: [9673]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=William_Randolph_Hearst_Papers_1874_1951_bulk_1927_1947_OAI'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=William_Randolph_Hearst_Papers_1874_1951_bulk_1927_1947_OAI%27})
[2024-11-05, 00:22:45 UTC] {logging_mixin.py:188} INFO - 10373 : success,     1 pages,      9 items,      2 solr items,     7 new items, solr count last updated: December 02, 2022 15:06:50.932958
[2024-11-05, 00:22:46 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 10425: [10425]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=HHBancroftRecords_OAI'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=HHBancroftRecords_OAI%27})
[2024-11-05, 00:22:47 UTC] {logging_mixin.py:188} INFO - 11167 : success,     1 pages,      6 items,      3 solr items,     3 new items, solr count last updated: December 02, 2022 15:06:50.512750
[2024-11-05, 00:22:48 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 11237: [11237]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=hiramjohnson_oai'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=hiramjohnson_oai%27})
[2024-11-05, 00:22:51 UTC] {logging_mixin.py:188} INFO - 11437 : success,     1 pages,     47 items,      9 solr items,    38 new items, solr count last updated: December 02, 2022 15:06:50.277300
[2024-11-05, 00:22:52 UTC] {logging_mixin.py:188} INFO - 11582 : success,     1 pages,      3 items,      3 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:50.173938
[2024-11-05, 00:22:53 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 11601: [11601]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=keithmchenrypond_oai'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=keithmchenrypond_oai%27})
[2024-11-05, 00:22:53 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 12553: [12553]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Ernest_O_Lawrence_Papers'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Ernest_O_Lawrence_Papers%27})
[2024-11-05, 00:22:54 UTC] {logging_mixin.py:188} INFO - 12740 : success,     1 pages,      5 items,      2 solr items,     3 new items, solr count last updated: December 02, 2022 15:06:49.418649
[2024-11-05, 00:22:55 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 13386: [13386]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=lahp'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=lahp%27})
[2024-11-05, 00:22:56 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 13710: [13710]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Magic_Theatre_Records_1967_1990'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Magic_Theatre_Records_1967_1990%27})
[2024-11-05, 00:22:57 UTC] {logging_mixin.py:188} INFO - 13943 : success,     1 pages,      3 items,      3 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:48.658172
[2024-11-05, 00:22:57 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 13961: [13961]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Robert_Marshall_Papers_1908_1939'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Robert_Marshall_Papers_1908_1939%27})
[2024-11-05, 00:22:58 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 14589: [14589]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Ynes_Mexia_papers'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Ynes_Mexia_papers%27})
[2024-11-05, 00:22:59 UTC] {logging_mixin.py:188} INFO - 16580 : success,     1 pages,      3 items,      3 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:46.308740
[2024-11-05, 00:23:00 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 17069: [17069]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=jamesphelan_oai'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=jamesphelan_oai%27})
[2024-11-05, 00:23:00 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 18689: [18689]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=annetterosenshinepapers'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=annetterosenshinepapers%27})
[2024-11-05, 00:23:02 UTC] {logging_mixin.py:188} INFO - 18772 : success,     1 pages,     10 items,     10 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:44.625813
[2024-11-05, 00:23:03 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 19580: [19580]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Schmidt_Lithograph_Records'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Schmidt_Lithograph_Records%27})
[2024-11-05, 00:23:05 UTC] {logging_mixin.py:188} INFO - 20587 : success,     1 pages,     33 items,     10 solr items,    23 new items, solr count last updated: December 02, 2022 15:06:43.286413
[2024-11-05, 00:23:06 UTC] {logging_mixin.py:188} INFO - 20753 : success,     1 pages,      8 items,      8 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:43.239596
[2024-11-05, 00:23:07 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 22164: [22164]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=noelsullivan_oai'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=noelsullivan_oai%27})
[2024-11-05, 00:23:09 UTC] {logging_mixin.py:188} INFO - 22392 : success,     1 pages,     18 items,     11 solr items,     7 new items, solr count last updated: December 02, 2022 15:06:42.167706
[2024-11-05, 00:23:09 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 22497: [22497]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=silvestreterrazas_oai'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=silvestreterrazas_oai%27})
[2024-11-05, 00:23:12 UTC] {logging_mixin.py:188} INFO - 23801 : success,     1 pages,     33 items,      1 solr items,    32 new items, solr count last updated: December 02, 2022 15:06:41.010693
[2024-11-05, 00:23:13 UTC] {logging_mixin.py:188} INFO - 23924 : success,     1 pages,      8 items,      2 solr items,     6 new items, solr count last updated: December 02, 2022 15:06:40.858653
[2024-11-05, 00:23:14 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 24518: [24518]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Philip_Whalen_Papers'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Philip_Whalen_Papers%27})
[2024-11-05, 00:23:15 UTC] {logging_mixin.py:188} INFO - 25158 : success,     1 pages,      1 items,      1 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:39.659762
[2024-11-05, 00:23:16 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 25597: [25597]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=calartresearcharchive'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=calartresearcharchive%27})
[2024-11-05, 00:23:16 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 26137: [26137]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=edwardothocresap_oai'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=edwardothocresap_oai%27})
[2024-11-05, 00:23:17 UTC] {logging_mixin.py:188} INFO - 26138 : success,     1 pages,      2 items,      2 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:39.226846
[2024-11-05, 00:23:18 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 26206: [26206]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=goldmanpapers'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=goldmanpapers%27})
[2024-11-05, 00:23:18 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 26207: [26207]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=sfjewishcc'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=sfjewishcc%27})
[2024-11-05, 00:23:20 UTC] {logging_mixin.py:188} INFO - 26390 : success,     1 pages,     10 items,     10 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:38.937725
[2024-11-05, 00:23:21 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 26693: [26693]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=fritz-metcalf'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=fritz-metcalf%27})
[2024-11-05, 00:23:22 UTC] {logging_mixin.py:188} INFO - 26916 : success,     1 pages,      6 items,      6 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:38.745273
[2024-11-05, 00:23:23 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 27157: [27157]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Otto_Stern_Papers'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=Otto_Stern_Papers%27})
[2024-11-05, 00:23:23 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 27435: [27435]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=sugoroku'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=sugoroku%27})
[2024-11-05, 00:23:44 UTC] {logging_mixin.py:188} INFO - 27571 : success,     5 pages,    455 items,    455 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:38.311218
[2024-11-05, 00:25:38 UTC] {logging_mixin.py:188} INFO - 27572 : success,    27 pages,   2609 items,   2609 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:38.301975
[2024-11-05, 00:25:39 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 27573: [27573]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=siberianphotos'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=siberianphotos%27})
[2024-11-05, 00:25:39 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 27648: [27648]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=librettos'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=librettos%27})
[2024-11-05, 00:25:44 UTC] {logging_mixin.py:188} INFO - 27649 : success,     1 pages,     99 items,     99 solr items,   0 same extent, solr count last updated: December 02, 2022 15:06:38.254755
[2024-11-05, 00:46:29 UTC] {logging_mixin.py:188} INFO - 27650 : success,   230 pages,  22913 items,  11906 solr items, 11007 new items, solr count last updated: December 02, 2022 15:06:38.242794
[2024-11-05, 00:46:29 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 28008: [28008]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=alphonsePinart_oai'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=alphonsePinart_oai%27})
[2024-11-05, 00:46:31 UTC] {logging_mixin.py:188} INFO - 28009 : success,     1 pages,     17 items,     17 solr items,   0 same extent, solr count last updated: October 30, 2023 11:46:46.110203
[2024-11-05, 00:46:32 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 28010: [28010]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=documentos_oai'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=documentos_oai%27})
[2024-11-05, 00:46:34 UTC] {logging_mixin.py:188} INFO - 28011 : success,     1 pages,     14 items,     14 solr items,   0 same extent, solr count last updated: October 30, 2023 11:46:46.083541
[2024-11-05, 00:46:34 UTC] {logging_mixin.py:188} INFO - ERROR fetching collection 28039: [28039]: unable to fetch page {'url': '[https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=tvtv_oai'}](https://digicoll.lib.berkeley.edu/oai2d?verb=ListRecords&metadataPrefix=marcxml&set=tvtv_oai%27})
[2024-11-05, 00:46:37 UTC] {logging_mixin.py:188} INFO - 28071 : success,     1 pages,     20 items,     20 solr items,   0 same extent, solr count last updated: November 02, 2023 14:31:44.636024
[2024-11-05, 00:46:38 UTC] {logging_mixin.py:188} INFO - 28072 : success,     1 pages,      3 items,      3 solr items,   0 same extent, solr count last updated: November 02, 2023 14:31:44.622278
[2024-11-05, 00:46:38 UTC] {logging_mixin.py:188} INFO - Review fetched data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#150/vernacular_metadata_2024-11-05T00:19:55/data/
[2024-11-05, 00:46:38 UTC] {logging_mixin.py:188} INFO - Review fetched data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#747/vernacular_metadata_2024-11-05T00:22:29/data/
[2024-11-05, 18:00:37 UTC] {taskinstance.py:441} ▼ Post task execution logs
[2024-11-05, 18:00:37 UTC] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/dags/rikolti/dags/shared_tasks/fetching_tasks.py", line 91, in fetch_endpoint_task
    version = fetched_collection.version
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'version'
```

**Comment by barbarahui** [comment]
@christinklez This should alleviate the problem where 503 errors from tind were causing the harvest by mapper type job to fail

**Comment by christinklez** [comment]
Just a quick update that I ran the batch of TIND validation job and all 67 reports generated perfectly. Thank you for this fix!
