### ISSUE TITLE
oac_mapper.py "No module named 'utils'" error

### ISSUE THREAD

**Issue by barbarahui** [ucldc/rikolti#184]
There is an import error for metadata-mapper/oac_mapper.py:

```
(.env) bhui@cdl-bhui-9m metadata-mapper % python tests.py
Traceback (most recent call last):
  File "/usr/local/dev/rikolti/metadata-mapper/tests.py", line 1, in <module>
    from lambda_function import lambda_handler
  File "/usr/local/dev/rikolti/metadata-mapper/lambda_function.py", line 7, in <module>
    from oac_mapper import OAC_Vernacular
  File "/usr/local/dev/rikolti/metadata-mapper/oac_mapper.py", line 7, in <module>
    from utils import exists, getprop, iterify
ModuleNotFoundError: No module named 'utils'
```
Which utils module is this referring to?

**Comment by barbarahui** [comment]
Resolved with this commit: https://github.com/ucldc/rikolti/commit/9c0380784774ccc1d11e8636c6c11babd8810a37
