### ISSUE TITLE
OAC Mapper failing to run properly

### ISSUE THREAD

**Issue by amywieliczka** [ucldc/rikolti#474]
Can't run OAC Mapper for collection 11747 (first collection I've tried - not sure how widespread this issue is):

```
Traceback (most recent call last):
  File "/Users/awieliczka/Projects/rikolti/metadata_mapper/map_registry_collections.py", line 68, in <module>
    map_endpoint(args.endpoint)
  File "/Users/awieliczka/Projects/rikolti/metadata_mapper/map_registry_collections.py", line 45, in map_endpoint
    return_val = lambda_shepherd.map_collection(
  File "/Users/awieliczka/Projects/rikolti/metadata_mapper/lambda_shepherd.py", line 89, in map_collection
    return_val = map_page(json.dumps(payload), {})
  File "/Users/awieliczka/Projects/rikolti/metadata_mapper/lambda_function.py", line 91, in map_page
    record.to_UCLDC()
  File "/Users/awieliczka/Projects/rikolti/metadata_mapper/mappers/mapper.py", line 123, in to_UCLDC
    mapped_data = {**mapped_data, **self.UCLDC_map()}
  File "/Users/awieliczka/Projects/rikolti/metadata_mapper/mappers/oac/oac_mapper.py", line 37, in UCLDC_map
    "spatial": self.map_spatial(),
  File "/Users/awieliczka/Projects/rikolti/metadata_mapper/mappers/oac/oac_mapper.py", line 151, in map_spatial
    coverage_data = iterify(getprop("coverage"))
TypeError: getprop() missing 1 required positional argument: 'path'
```

**Comment by lthurston** [comment]
I'm taking a look!

**Comment by lthurston** [comment]
Ok, sorry about that. Not sure how that came to pass.

You probably are doing this, and this is just as much a note to self, but there are some unpublished collections in here, so map thusly to maximize delight:

`map_registry_collections.map_endpoint("https://registry.cdlib.org/api/v1/rikoltifetcher/?format=json&harvest_type=OAC&ready_for_publication=true")`

**Comment by christinklez** [comment]
Closing this issue as we will not be developing the OAC fetcher/mapper.
