### ISSUE TITLE
Generate and review validation reports: arck_oai

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#573]

**Comment by gamontoya** [comment]
@amywieliczka @barbarahui @christinklez 

Failed at `map_endpoint_tasks`

`Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/utils_by_mapper_type.py", line 44, in map_endpoint_task
    mapper_job_results = map_endpoint(endpoint, limit)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/map_registry_collections.py", line 54, in map_endpoint
    map_result = lambda_shepherd.map_collection(
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/lambda_shepherd.py", line 114, in map_collection
    mapped_page = map_page(collection_id, page, collection)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/lambda_function.py", line 88, in map_page
    record.to_UCLDC()
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/mappers/mapper.py", line 135, in to_UCLDC
    self.mapped_data = {k: v() if isinstance(v, Callable) else v for (k, v)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/mappers/mapper.py", line 135, in <dictcomp>
    self.mapped_data = {k: v() if isinstance(v, Callable) else v for (k, v)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/mappers/oai/content_dm/contentdm_mapper.py", line 22, in map_is_shown_at
    return self.get_matching_identifier(last=True)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/mappers/oai/content_dm/contentdm_mapper.py", line 128, in get_matching_identifier
    identifiers = [i for i in self.source_metadata.get("identifier", [])
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/mappers/oai/content_dm/contentdm_mapper.py", line 129, in <listcomp>
    if self.identifier_match in i]
TypeError: argument of type 'NoneType' is not iterable
[2023-11-15, 00:31:39 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=validate_by_mapper_type, task_id=map_endpoint_task, execution_date=20231115T003028, start_date=20231115T003134, end_date=20231115T003139
[2023-11-15, 00:31:39 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 1956 for task map_endpoint_task (argument of type 'NoneType' is not iterable; 29412)
[2023-11-15, 00:31:39 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2023-11-15, 00:31:39 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check`

**Comment by amywieliczka** [comment]
https://github.com/ucldc/rikolti/pull/631 - untested but I believe this will resolve this error.

**Comment by amywieliczka** [comment]
Just merged #631 - this should be good to go again.

**Comment by christinklez** [comment]
@amywieliczka @barbarahui -- this hit another error at `map_endpoint_task`:

```
[2023-11-17, 18:28:27 UTC] {{taskinstance.py:1824}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/utils_by_mapper_type.py", line 44, in map_endpoint_task
    mapper_job_results = map_endpoint(endpoint, limit)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/map_registry_collections.py", line 54, in map_endpoint
    map_result = lambda_shepherd.map_collection(
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/lambda_shepherd.py", line 110, in map_collection
    page_list = get_vernacular_pages(collection_id)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/lambda_shepherd.py", line 68, in get_vernacular_pages
    page_list = [page['Key'] for page in resp['Contents']]
KeyError: 'Contents'
[2023-11-17, 18:28:27 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=validate_by_mapper_type, task_id=map_endpoint_task, execution_date=20231115T003028, start_date=20231117T182819, end_date=20231117T182827
[2023-11-17, 18:28:27 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 1998 for task map_endpoint_task ('Contents'; 32518)
[2023-11-17, 18:28:28 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2023-11-17, 18:28:28 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by amywieliczka** [comment]
I just made an update that should get us a better error message - currently re-running the task here: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?root=&dag_run_id=manual__2023-11-15T00%3A30%3A28%2B00%3A00&task_id=map_endpoint_task&tab=logs

**Comment by amywieliczka** [comment]
Okay! Here it is: 
https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?root=&dag_run_id=manual__2023-11-15T00%3A30%3A28%2B00%3A00&task_id=map_endpoint_task&tab=logs

Can you spot the issue from the log output?

**Comment by christinklez** [comment]
@amywieliczka, thank you so much!! It now fails at `validate_endpoint_task` (final step)!

```
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/utils_by_mapper_type.py", line 68, in validate_endpoint_task
    num_rows, file_location = create_collection_validation_csv(
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 113, in create_collection_validation_csv
    result = validate_collection(collection_id, **options)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 52, in validate_collection
    for page_id in utilities.get_files(collection_id, "mapped_metadata"):
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/utilities.py", line 81, in get_files
    raise Exception(
Exception: False: Error listing files at s3://rikolti-data/27585/mapped_metadata/
False: Check that mapped_metadata exists at https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#{collection_id}/
False: 'Contents'
[2023-11-17, 19:05:03 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=validate_by_mapper_type, task_id=validate_endpoint_task, execution_date=20231115T003028, start_date=20231117T190458, end_date=20231117T190503
[2023-11-17, 19:05:03 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 2001 for task validate_endpoint_task (False: Error listing files at s3://rikolti-data/27585/mapped_metadata/
False: Check that mapped_metadata exists at https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#{collection_id}/
False: 'Contents'; 390)
[2023-11-17, 19:05:04 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2023-11-17, 19:05:04 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by amywieliczka** [comment]
@christinklez Well, this says there's an issue listing files at s3://rikolti-data/27585/mapped_metadata/

Have you checked s3? Was collection 27585 mapped?

**Comment by christinklez** [comment]
27585 is not listed here: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html

(I see 27584 then 27586 in the ordered list of collection folders.)

27585's contents would presumably be here: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27585/

Looks like the collection has 7 records currently published: https://calisphere.org/collections/27585/

**Comment by gamontoya** [comment]
@christinklez This is ready for notes review/synthesizing

**Comment by christinklez** [comment]
Fixes requested here: https://github.com/ucldc/rikolti/issues/653

**Comment by christinklez** [comment]
[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27564/vernacular_metadata_2024-01-25T21:31:21/mapped_metadata_2024-01-25T21:32:04/validation_2024-01-25T21:32:28.csv
[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27564/vernacular_metadata_2024-01-25T21:31:21/mapped_metadata_2024-01-25T21:32:04/data/

[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27582/vernacular_metadata_2024-01-25T21:31:28/mapped_metadata_2024-01-25T21:32:06/validation_2024-01-25T21:32:28.csv
[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27582/vernacular_metadata_2024-01-25T21:31:28/mapped_metadata_2024-01-25T21:32:06/data/

[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27583/vernacular_metadata_2024-01-25T21:31:29/mapped_metadata_2024-01-25T21:32:07/validation_2024-01-25T21:32:29.csv
[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27583/vernacular_metadata_2024-01-25T21:31:29/mapped_metadata_2024-01-25T21:32:07/data/

[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27584/vernacular_metadata_2024-01-25T21:31:29/mapped_metadata_2024-01-25T21:32:07/validation_2024-01-25T21:32:30.csv
[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27584/vernacular_metadata_2024-01-25T21:31:29/mapped_metadata_2024-01-25T21:32:07/data/

[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27586/vernacular_metadata_2024-01-25T21:31:33/mapped_metadata_2024-01-25T21:32:09/validation_2024-01-25T21:32:31.csv
[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27586/vernacular_metadata_2024-01-25T21:31:33/mapped_metadata_2024-01-25T21:32:09/data/

[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27587/vernacular_metadata_2024-01-25T21:31:38/mapped_metadata_2024-01-25T21:32:11/validation_2024-01-25T21:32:35.csv
[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27587/vernacular_metadata_2024-01-25T21:31:38/mapped_metadata_2024-01-25T21:32:11/data/

[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27588/vernacular_metadata_2024-01-25T21:31:50/mapped_metadata_2024-01-25T21:32:16/validation_2024-01-25T21:32:36.csv
[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27588/vernacular_metadata_2024-01-25T21:31:50/mapped_metadata_2024-01-25T21:32:16/data/

[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27589/vernacular_metadata_2024-01-25T21:31:56/mapped_metadata_2024-01-25T21:32:19/validation_2024-01-25T21:32:37.csv
[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27589/vernacular_metadata_2024-01-25T21:31:56/mapped_metadata_2024-01-25T21:32:19/data/

[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27590/vernacular_metadata_2024-01-25T21:31:56/mapped_metadata_2024-01-25T21:32:19/validation_2024-01-25T21:32:37.csv
[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27590/vernacular_metadata_2024-01-25T21:31:56/mapped_metadata_2024-01-25T21:32:19/data/

[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27591/vernacular_metadata_2024-01-25T21:31:57/mapped_metadata_2024-01-25T21:32:20/validation_2024-01-25T21:32:38.csv
[2024-01-25, 21:32:38 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27591/vernacular_metadata_2024-01-25T21:31:57/mapped_metadata_2024-01-25T21:32:20/data/
