### ISSUE TITLE
Generate and review validation reports: chula_vista_pl_contentdm_oai_dc -- endpoint issue; contacted contributor

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#575]
- **Step 2: Generate reports** [status: in progress --> ready for review]
  - [ ] Generate validation reports (run `validate_by_mapper DAG`): https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2023-11-16T00%3A46%3A50%2B00%3A00
  - [ ] Add a comment (in this issue) to the output URLs
  - [ ] Download the validation reports locally; prepend the collection registry number to the filename
  - [ ] Upload validation reports to the [Rikolti Data Validation](https://drive.google.com/drive/folders/1AgDPsz6oyDhsfgRuLyjomaXYgE1sPLNT) folder
- **Step 3: Review reports**  [status: ready for review --> review in progress]
  - [ ] Review [sample collections validation reports](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1143782640); leave notes in the spreadsheet
  - [ ] Quickly (and not very deeply) scan through other validation reports (to identify if any new metadata fields surface)
  - [ ] Synthesize notes at the [mapper level](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1100474517)
  - [ ] Share an update (and surface any anomalies) during a weekly check-in (Mondays at 3:00pm)
- **Step 4: Have data validation issues? Address & resolve validation issues (synthesized mapper-level):**
  - [ ] Create a new issue (“Validation results: Rikolti mapper name“) and report/request CIC fixes & investigations. Assign to CIC.
  - [ ] Add a comment to link to the new “validation results” issue.
  - [ ] Add a “blocked/paused” label to this issue. Include a status note in this issue title (e,g., HOLD for CIC fixes; HOLD for code review; etc.) 
  - [ ] Move this issue back to the “To Do” pile.
- [Re-generate & re-review (repeat steps 2-3 above, as needed.]
- **Step 5: Have acceptable validation reports?**
  - [ ] Move the valid (accepted) reports to the “VALID” folder in google drive.
  - [ ] Update the [mapper progress spreadsheet](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1100474517); indicate that the mapper is accepted

**Comment by christinklez** [comment]
```
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 415, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f1a7b2f32e0>, 'Connection to archives.chulavistalibrary.com timed out. (connect timeout=None)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='archives.chulavistalibrary.com', port=2009): Max retries exceeded with url: /cgi-bin/oai.exe/oai.php?verb=ListMetadataFormats (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1a7b2f32e0>, 'Connection to archives.chulavistalibrary.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/utils_by_mapper_type.py", line 33, in fetch_endpoint_task
    fetcher_job_result = fetch_endpoint(endpoint, limit, logger)
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/fetch_registry_collections.py", line 54, in fetch_endpoint
    fetch_result = lambda_function.fetch_collection(collection, None)
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/lambda_function.py", line 33, in fetch_collection
    fetcher = fetcher_class(payload)
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/fetchers/oai_fetcher.py", line 41, in __init__
    self.metadata_prefix = self.get_md_prefix_from_feed()
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/fetchers/oai_fetcher.py", line 49, in get_md_prefix_from_feed
    md_formats = [x for x in sickle_client.ListMetadataFormats()]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/sickle/app.py", line 195, in ListMetadataFormats
    return self.iterator(self, params)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/sickle/iterator.py", line 135, in __init__
    super(OAIItemIterator, self).__init__(sickle, params, ignore_deleted)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/sickle/iterator.py", line 46, in __init__
    self._next_response()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/sickle/iterator.py", line 138, in _next_response
    super(OAIItemIterator, self)._next_response()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/sickle/iterator.py", line 84, in _next_response
    self.oai_response = self.sickle.harvest(**params)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/sickle/app.py", line 121, in harvest
    http_response = self._request(kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/sickle/app.py", line 137, in _request
    return requests.get(self.endpoint, params=kwargs, **self.request_args)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='archives.chulavistalibrary.com', port=2009): Max retries exceeded with url: /cgi-bin/oai.exe/oai.php?verb=ListMetadataFormats (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1a7b2f32e0>, 'Connection to archives.chulavistalibrary.com timed out. (connect timeout=None)'))
[2023-11-16, 00:49:26 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=validate_by_mapper_type, task_id=fetch_endpoint_task, execution_date=20231116T004650, start_date=20231116T004714, end_date=20231116T004926
[2023-11-16, 00:49:26 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 1962 for task fetch_endpoint_task (HTTPConnectionPool(host='archives.chulavistalibrary.com', port=2009): Max retries exceeded with url: /cgi-bin/oai.exe/oai.php?verb=ListMetadataFormats (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f1a7b2f32e0>, 'Connection to archives.chulavistalibrary.com timed out. (connect timeout=None)')); 9966)
[2023-11-16, 00:49:26 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2023-11-16, 00:49:26 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check

```

**Comment by christinklez** [comment]
@aturner The endpoint does not seem to work. https://calisphere.org/institution/59/collections/ -- did they possibly move systems?
