### ISSUE TITLE
Generate and review validation reports: burbank_islandora

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#581]
- **Step 2: Generate reports** [status: in progress --> ready for review]
  - [x] Generate validation reports (run `validate_by_mapper DAG`): https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2023-11-13T22%3A25%3A28%2B00%3A00
  - [x] Add a comment (in this issue) to the output URLs
  - [x] Download the validation reports locally; prepend the collection registry number to the filename
  - [x] Upload validation reports to the [Rikolti Data Validation](https://drive.google.com/drive/folders/1AgDPsz6oyDhsfgRuLyjomaXYgE1sPLNT) folder
- **Step 3: Review reports**  [status: ready for review --> review in progress]
  - [x] Review [sample collections validation reports](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1143782640); leave notes in the spreadsheet
  - [x] Quickly (and not very deeply) scan through other validation reports (to identify if any new metadata fields surface)
  - [x] Synthesize notes at the [mapper level](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1100474517)
  - [x] Share an update (and surface any anomalies) during a weekly check-in (Mondays at 3:00pm)
- **Step 4: Have data validation issues? Address & resolve validation issues (synthesized mapper-level):**
  - [ ] Create a new issue (“Validation results: Rikolti mapper name“) and report/request CIC fixes & investigations. Assign to CIC.
  - [ ] Add a comment to link to the new “validation results” issue.
  - [ ] Add a “blocked/paused” label to this issue. Include a status note in this issue title (e,g., HOLD for CIC fixes; HOLD for code review; etc.) 
  - [ ] Move this issue back to the “To Do” pile.
- [Re-generate & re-review (repeat steps 2-3 above, as needed.]
- **Step 5: Have acceptable validation reports?**
  - [x] Move the valid (accepted) reports to the “VALID” folder in google drive.
  - [x] Update the [mapper progress spreadsheet](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1100474517); indicate that the mapper is accepted

**Comment by gamontoya** [comment]
@amywieliczka @barbarahui @christinklez 

The reports fail at `map_endpoint_task`:

`Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/utils_by_mapper_type.py", line 44, in map_endpoint_task
    mapper_job_results = map_endpoint(endpoint, limit)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/map_registry_collections.py", line 54, in map_endpoint
    map_result = lambda_shepherd.map_collection(
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/lambda_shepherd.py", line 114, in map_collection
    mapped_page = map_page(collection_id, page, collection)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/lambda_function.py", line 88, in map_page
    record.to_UCLDC()
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/mappers/mapper.py", line 131, in to_UCLDC
    mapped_data = {**mapped_data, **self.UCLDC_map()}
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/mappers/oai/islandora/burbank_mapper.py", line 11, in UCLDC_map
    "date": self.map_date()
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/mappers/oai/islandora/burbank_mapper.py", line 31, in map_date
    return [d for d in dates if self.date_regex.search(d) is None]
TypeError: 'function' object is not iterable
[2023-11-13, 22:27:46 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=validate_by_mapper_type, task_id=map_endpoint_task, execution_date=20231113T222528, start_date=20231113T222745, end_date=20231113T222746
[2023-11-13, 22:27:46 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 1945 for task map_endpoint_task ('function' object is not iterable; 15388)
[2023-11-13, 22:27:46 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2023-11-13, 22:27:46 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check`

**Comment by barbarahui** [comment]
@amywieliczka @lthurston I think I see the problem. https://github.com/ucldc/rikolti/blob/main/metadata_mapper/mappers/oai/islandora/burbank_mapper.py#L31C1 should be:

`return [d for d in dates() if self.date_regex.search(d) is None]`

not:

`return [d for d in dates if self.date_regex.search(d) is None]`

**Comment by barbarahui** [comment]
Fix: https://github.com/ucldc/rikolti/pull/649

**Comment by barbarahui** [comment]
@christinklez This should be fixed. Can you try running again?

**Comment by christinklez** [comment]
@barbarahui error at `validate_endpoint_task`

Looks like a similar error message as csu_sac_oai_dc & quartex

Full log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2023-11-13T22%3A25%3A28%2B00%3A00&task_id=validate_endpoint_task&tab=logs

```
[2023-11-29, 21:16:06 UTC] {{logging_mixin.py:150}} INFO - Output 271 rows to 27138/vernacular_metadata_2023-11-29T21:08:17/mapped_metadata_2023-11-29T21:15:08/validation_2023-11-29T21:16:06.csv
[2023-11-29, 21:16:06 UTC] {{taskinstance.py:1824}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/utils_by_mapper_type.py", line 116, in validate_endpoint_task
    s3_path = urlparse(collection['data_uri'])
TypeError: 'int' object is not subscriptable
[2023-11-29, 21:16:06 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=validate_by_mapper_type, task_id=validate_endpoint_task, execution_date=20231113T222528, start_date=20231129T211536, end_date=20231129T211606
[2023-11-29, 21:16:06 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 2103 for task validate_endpoint_task ('int' object is not subscriptable; 14437)
[2023-11-29, 21:16:06 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2023-11-29, 21:16:06 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check

```

**Comment by christinklez** [comment]
[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27128/vernacular_metadata_2023-11-29T21:06:57/mapped_metadata_2023-11-29T21:08:27/validation_2023-11-29T23:38:22.csv
[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27128/vernacular_metadata_2023-11-29T21:06:57/mapped_metadata_2023-11-29T21:08:27/data/

[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27129/vernacular_metadata_2023-11-29T21:07:16/mapped_metadata_2023-11-29T21:10:00/validation_2023-11-29T23:38:32.csv
[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27129/vernacular_metadata_2023-11-29T21:07:16/mapped_metadata_2023-11-29T21:10:00/data/

[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27130/vernacular_metadata_2023-11-29T21:07:40/mapped_metadata_2023-11-29T21:12:07/validation_2023-11-29T23:38:33.csv
[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27130/vernacular_metadata_2023-11-29T21:07:40/mapped_metadata_2023-11-29T21:12:07/data/

[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27131/vernacular_metadata_2023-11-29T21:07:42/mapped_metadata_2023-11-29T21:12:17/validation_2023-11-29T23:38:39.csv
[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27131/vernacular_metadata_2023-11-29T21:07:42/mapped_metadata_2023-11-29T21:12:17/data/

[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27132/vernacular_metadata_2023-11-29T21:07:56/mapped_metadata_2023-11-29T21:13:27/validation_2023-11-29T23:38:44.csv
[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27132/vernacular_metadata_2023-11-29T21:07:56/mapped_metadata_2023-11-29T21:13:27/data/

[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27133/vernacular_metadata_2023-11-29T21:08:07/mapped_metadata_2023-11-29T21:14:25/validation_2023-11-29T23:38:47.csv
[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27133/vernacular_metadata_2023-11-29T21:08:07/mapped_metadata_2023-11-29T21:14:25/data/

[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27134/vernacular_metadata_2023-11-29T21:08:10/mapped_metadata_2023-11-29T21:14:37/validation_2023-11-29T23:38:50.csv
[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27134/vernacular_metadata_2023-11-29T21:08:10/mapped_metadata_2023-11-29T21:14:37/data/

[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27135/vernacular_metadata_2023-11-29T21:08:13/mapped_metadata_2023-11-29T21:14:50/validation_2023-11-29T23:38:51.csv
[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27135/vernacular_metadata_2023-11-29T21:08:13/mapped_metadata_2023-11-29T21:14:50/data/

[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27136/vernacular_metadata_2023-11-29T21:08:14/mapped_metadata_2023-11-29T21:14:52/validation_2023-11-29T23:38:52.csv
[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27136/vernacular_metadata_2023-11-29T21:08:14/mapped_metadata_2023-11-29T21:14:52/data/

[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27137/vernacular_metadata_2023-11-29T21:08:16/mapped_metadata_2023-11-29T21:15:03/validation_2023-11-29T23:38:52.csv
[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27137/vernacular_metadata_2023-11-29T21:08:16/mapped_metadata_2023-11-29T21:15:03/data/

[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27138/vernacular_metadata_2023-11-29T21:08:17/mapped_metadata_2023-11-29T21:15:08/validation_2023-11-29T23:38:55.csv
[2023-11-29, 23:38:55 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27138/vernacular_metadata_2023-11-29T21:08:17/mapped_metadata_2023-11-29T21:15:08/data/

**Comment by gamontoya** [comment]
@christinklez Looks like this is ready to go. I'll take it from here.

**Comment by christinklez** [comment]
Validation fixes requested: https://github.com/ucldc/rikolti/issues/666

**Comment by christinklez** [comment]
[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27128/vernacular_metadata_2023-12-20T23:47:34/mapped_metadata_2023-12-20T23:49:16/validation_2023-12-20T23:56:55.csv
[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27128/vernacular_metadata_2023-12-20T23:47:34/mapped_metadata_2023-12-20T23:49:16/data/

[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27129/vernacular_metadata_2023-12-20T23:47:54/mapped_metadata_2023-12-20T23:50:54/validation_2023-12-20T23:57:01.csv
[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27129/vernacular_metadata_2023-12-20T23:47:54/mapped_metadata_2023-12-20T23:50:54/data/

[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27130/vernacular_metadata_2023-12-20T23:48:23/mapped_metadata_2023-12-20T23:53:11/validation_2023-12-20T23:57:02.csv
[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27130/vernacular_metadata_2023-12-20T23:48:23/mapped_metadata_2023-12-20T23:53:11/data/

[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27131/vernacular_metadata_2023-12-20T23:48:25/mapped_metadata_2023-12-20T23:53:21/validation_2023-12-20T23:57:06.csv
[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27131/vernacular_metadata_2023-12-20T23:48:25/mapped_metadata_2023-12-20T23:53:21/data/

[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27132/vernacular_metadata_2023-12-20T23:48:41/mapped_metadata_2023-12-20T23:54:35/validation_2023-12-20T23:57:09.csv
[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27132/vernacular_metadata_2023-12-20T23:48:41/mapped_metadata_2023-12-20T23:54:35/data/

[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27133/vernacular_metadata_2023-12-20T23:48:54/mapped_metadata_2023-12-20T23:55:39/validation_2023-12-20T23:57:10.csv
[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27133/vernacular_metadata_2023-12-20T23:48:54/mapped_metadata_2023-12-20T23:55:39/data/

[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27134/vernacular_metadata_2023-12-20T23:48:57/mapped_metadata_2023-12-20T23:55:52/validation_2023-12-20T23:57:12.csv
[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27134/vernacular_metadata_2023-12-20T23:48:57/mapped_metadata_2023-12-20T23:55:52/data/

[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27135/vernacular_metadata_2023-12-20T23:49:00/mapped_metadata_2023-12-20T23:56:04/validation_2023-12-20T23:57:12.csv
[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27135/vernacular_metadata_2023-12-20T23:49:00/mapped_metadata_2023-12-20T23:56:04/data/

[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27136/vernacular_metadata_2023-12-20T23:49:01/mapped_metadata_2023-12-20T23:56:06/validation_2023-12-20T23:57:13.csv
[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27136/vernacular_metadata_2023-12-20T23:49:01/mapped_metadata_2023-12-20T23:56:06/data/

[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27137/vernacular_metadata_2023-12-20T23:49:03/mapped_metadata_2023-12-20T23:56:17/validation_2023-12-20T23:57:13.csv
[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27137/vernacular_metadata_2023-12-20T23:49:03/mapped_metadata_2023-12-20T23:56:17/data/

[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27138/vernacular_metadata_2023-12-20T23:49:05/mapped_metadata_2023-12-20T23:56:21/validation_2023-12-20T23:57:15.csv
[2023-12-20, 23:57:15 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27138/vernacular_metadata_2023-12-20T23:49:05/mapped_metadata_2023-12-20T23:56:21/data/

**Comment by christinklez** [comment]
@gamontoya: fresh validation reports, dated Dec 20 are ready for your re-review! Thanks!
