### ISSUE TITLE
Generate and review validation reports: omeka_nothumb -- [empty mapped metadata page; also a very large collection: #27143]

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#586]
- **Step 2: Generate reports** [status: in progress --> ready for review]
  - [x] Generate validation reports (run `validate_by_mapper DAG`): https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2023-11-28T23%3A43%3A52%2B00%3A00
  - [x] Add a comment (in this issue) to the output URLs
  - [x] Download the validation reports locally; prepend the collection registry number to the filename
  - [x] Upload validation reports to the [Rikolti Data Validation](https://drive.google.com/drive/folders/1AgDPsz6oyDhsfgRuLyjomaXYgE1sPLNT) folder
- **Step 3: Review reports**  [status: ready for review --> review in progress]
  - [x] Review [sample collections validation reports](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1143782640); leave notes in the spreadsheet
  - [x] Quickly (and not very deeply) scan through other validation reports (to identify if any new metadata fields surface)
  - [x] Synthesize notes at the [mapper level](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1100474517)
  - [x] Share an update (and surface any anomalies) during a weekly check-in (Mondays at 3:00pm)
- **Step 4: Have data validation issues? Address & resolve validation issues (synthesized mapper-level):**
  - [ ] Create a new issue (“Validation results: Rikolti mapper name“) and report/request CIC fixes & investigations. Assign to CIC.
  - [ ] Add a comment to link to the new “validation results” issue.
  - [ ] Add a “blocked/paused” label to this issue. Include a status note in this issue title (e,g., HOLD for CIC fixes; HOLD for code review; etc.) 
  - [ ] Move this issue back to the “To Do” pile.
- [Re-generate & re-review (repeat steps 2-3 above, as needed.]
- **Step 5: Have acceptable validation reports?**
  - [x] Move the valid (accepted) reports to the “VALID” folder in google drive.
  - [x] Update the [mapper progress spreadsheet](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1100474517); indicate that the mapper is accepted

**Comment by gamontoya** [comment]
@amywieliczka @barbarahui I tried to run the mapper for omeka_nothumb and ran into this error which I don't know how to interpret.

[https://registry.cdlib.org/admin/library_collection/collection/?mapper_type=omeka_nothumb](https://registry.cdlib.org/admin/library_collection/collection/?mapper_type=omeka_nothumb)

---

```
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/utils_by_mapper_type.py", line 33, in fetch_endpoint_task
    fetcher_job_result = fetch_endpoint(endpoint, limit, logger)
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/fetch_registry_collections.py", line 54, in fetch_endpoint
    fetch_result = lambda_function.fetch_collection(collection, None)
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/lambda_function.py", line 55, in fetch_collection
    fetch_status.extend(fetch_collection(next_page, {}))
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/lambda_function.py", line 55, in fetch_collection
    fetch_status.extend(fetch_collection(next_page, {}))
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/lambda_function.py", line 55, in fetch_collection
    fetch_status.extend(fetch_collection(next_page, {}))
  [Previous line repeated 806 more times]
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/lambda_function.py", line 34, in fetch_collection
    fetch_status['document_count'] = fetcher.fetch_page()
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/fetchers/Fetcher.py", line 98, in fetch_page
    self.fetchtos3(content)
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/fetchers/Fetcher.py", line 62, in fetchtos3
    s3_client = boto3.client('s3')
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/boto3/__init__.py", line 92, in client
    return _get_default_session().client(*args, **kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/session.py", line 976, in create_client
    client = client_creator.create_client(
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 155, in create_client
    client_args = self._get_client_args(
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 485, in _get_client_args
    return args_creator.get_client_args(
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/args.py", line 148, in get_client_args
    ruleset_resolver = self._build_endpoint_resolver(
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/args.py", line 555, in _build_endpoint_resolver
    return EndpointRulesetResolver(
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/regions.py", line 469, in __init__
    self._provider = EndpointProvider(
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 704, in __init__
    self.ruleset = RuleSet(**ruleset_data, partitions=partition_data)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 658, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 658, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in __init__
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 533, in <listcomp>
    self.rules = [RuleCreator.create(**rule) for rule in rules]
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 572, in create
    return rule_class(**kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/endpoint_provider.py", line 445, in __init__
    super().__init__(**kwargs)
RecursionError: maximum recursion depth exceeded while calling a Python object
[2023-11-02, 19:40:41 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=validate_by_mapper_type, task_id=fetch_endpoint_task, execution_date=20231102T192948, start_date=20231102T193013, end_date=20231102T194041
[2023-11-02, 19:40:41 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 1918 for task fetch_endpoint_task (maximum recursion depth exceeded while calling a Python object; 2269)
[2023-11-02, 19:40:41 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2023-11-02, 19:40:41 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by aturner** [comment]
Their OAI-PMH endpoint seems to be working fine:

https://history.santacruzpl.org/omeka/oai-pmh-repository/request/?verb=ListSets

https://history.santacruzpl.org/omeka/oai-pmh-repository/request/?verb=ListRecords&metadataPrefix=oai_dc&set=6

**Comment by barbarahui** [comment]
I reran the dag after versioning was deployed to get a new stack trace. Log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2023-11-28T23%3A43%3A52%2B00%3A00&task_id=fetch_endpoint_task&tab=logs

Collection 27143 has 30,000+ records.

**Comment by christinklez** [comment]
In case this is helpful info, Santa Cruz Public Libraries is using two mappers: https://registry.cdlib.org/admin/library_collection/collection/?ready_for_publication__exact=1&repository__id__exact=245

7 collections use "omeka"
3 collections use "omeka_nothumb"
They are all being served by this endpoint: https://history.santacruzpl.org/omeka/oai-pmh-repository/request/?verb=ListSets

We were able to generate validation reports for the "omeka" set. But are running into errors with the "omeka_nothumb" set.

**Comment by amywieliczka** [comment]
This looks to me like a garbage collection issue of the s3 client that I walked straight into. I believe with the updates made in #675, this will be moot - will investigate again once that's merged in.

**Comment by christinklez** [comment]
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27146/vernacular_metadata_2024-01-24T02:17:10/mapped_metadata_2024-01-24T03:26:58/validation_2024-01-24T03:30:00.csv
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27146/vernacular_metadata_2024-01-24T02:17:10/mapped_metadata_2024-01-24T03:26:58/data/

[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27148/vernacular_metadata_2024-01-24T02:17:34/mapped_metadata_2024-01-24T03:27:32/validation_2024-01-24T03:30:16.csv
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27148/vernacular_metadata_2024-01-24T02:17:34/mapped_metadata_2024-01-24T03:27:32/data/

[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} WARNING - ------------------------------------------------------------
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} WARNING - -------------------- Validation Errors ---------------------
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} WARNING - ------------------------------------------------------------
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} WARNING -  Collection 27143: No mapped metadata found for 27143 page 27143/vernacular_metadata_2024-01-24T01:54:47/mapped_metadata_2024-01-24T02:18:28/data/10.jsonl. Aborting. 
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} WARNING - Traceback (most recent call last):
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} WARNING -   File "/usr/local/airflow/dags/rikolti/dags/utils_by_mapper_type.py", line 171, in validate_endpoint_task
    num_rows, version_page = create_collection_validation_csv(
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 217, in create_collection_validation_csv
    result = validate_collection(collection_id, mapped_page_paths, **options)
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 66, in validate_collection
    rikolti_ids, new_ids = validate_page(collection_id, page_path, validator)
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 171, in validate_page
    raise ValueError(
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} WARNING - ValueError: No mapped metadata found for 27143 page 27143/vernacular_metadata_2024-01-24T01:54:47/mapped_metadata_2024-01-24T02:18:28/data/10.jsonl. Aborting.
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} WARNING - <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} INFO - ************************************************************
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} INFO - 1 collections encountered validation errors
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} INFO - please validate manually: [27143]
[2024-01-24, 03:30:16 UTC] {{logging_mixin.py:150}} INFO - ************************************************************
[2024-01-24, 03:30:16 UTC] {{python.py:183}} INFO - Done. Returned value was: ['27146/vernacular_metadata_2024-01-24T02:17:10/mapped_metadata_2024-01-24T03:26:58/validation_2024-01-24T03:30:00.csv', '27148/vernacular_metadata_2024-01-24T02:17:34/mapped_metadata_2024-01-24T03:27:32/validation_2024-01-24T03:30:16.csv']
[

**Comment by christinklez** [comment]
[2024-02-03, 01:42:33 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27143/vernacular_metadata_2024-02-02T23:56:32/mapped_metadata_2024-02-03T00:16:25/validation_2024-02-03T01:42:13.csv
[2024-02-03, 01:42:33 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27143/vernacular_metadata_2024-02-02T23:56:32/mapped_metadata_2024-02-03T00:16:25/data/

[2024-02-03, 01:42:33 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27146/vernacular_metadata_2024-02-03T00:15:23/mapped_metadata_2024-02-03T01:35:17/validation_2024-02-03T01:42:19.csv
[2024-02-03, 01:42:33 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27146/vernacular_metadata_2024-02-03T00:15:23/mapped_metadata_2024-02-03T01:35:17/data/

[2024-02-03, 01:42:33 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27148/vernacular_metadata_2024-02-03T00:15:42/mapped_metadata_2024-02-03T01:35:38/validation_2024-02-03T01:42:33.csv
[2024-02-03, 01:42:33 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27148/vernacular_metadata_2024-02-03T00:15:42/mapped_metadata_2024-02-03T01:35:38/data/

**Comment by christinklez** [comment]
Accepted on 2024-02-05!
