### ISSUE TITLE
Generate and review validation reports: pspl_oai_dc

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#587]
- **Step 2: Generate reports** [status: in progress --> ready for review]
  - [x] Generate validation reports (run `validate_by_mapper DAG`): https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2023-11-17T17%3A06%3A06%2B00%3A00
  - [x] Add a comment (in this issue) to the output URLs
  - [x] Download the validation reports locally; prepend the collection registry number to the filename
  - [x] Upload validation reports to the [Rikolti Data Validation](https://drive.google.com/drive/folders/1AgDPsz6oyDhsfgRuLyjomaXYgE1sPLNT) folder
- **Step 3: Review reports**  [status: ready for review --> review in progress]
  - [x] Review [sample collections validation reports](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1143782640); leave notes in the spreadsheet
  - [x] Quickly (and not very deeply) scan through other validation reports (to identify if any new metadata fields surface)
  - [x] Synthesize notes at the [mapper level](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1100474517)
  - [x] Share an update (and surface any anomalies) during a weekly check-in (Mondays at 3:00pm)
- **Step 4: Have data validation issues? Address & resolve validation issues (synthesized mapper-level):**
  - [ ] Create a new issue (“Validation results: Rikolti mapper name“) and report/request CIC fixes & investigations. Assign to CIC.
  - [ ] Add a comment to link to the new “validation results” issue.
  - [ ] Add a “blocked/paused” label to this issue. Include a status note in this issue title (e,g., HOLD for CIC fixes; HOLD for code review; etc.) 
  - [ ] Move this issue back to the “To Do” pile.
- [Re-generate & re-review (repeat steps 2-3 above, as needed.]
- **Step 5: Have acceptable validation reports?**
  - [x] Move the valid (accepted) reports to the “VALID” folder in google drive.
  - [x] Update the [mapper progress spreadsheet](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1100474517); indicate that the mapper is accepted

**Comment by christinklez** [comment]
Fails at `map_endpoint_task`:

```
[2023-11-17, 17:06:46 UTC] {{taskinstance.py:1824}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/utils_by_mapper_type.py", line 44, in map_endpoint_task
    mapper_job_results = map_endpoint(endpoint, limit)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/map_registry_collections.py", line 54, in map_endpoint
    map_result = lambda_shepherd.map_collection(
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/lambda_shepherd.py", line 114, in map_collection
    mapped_page = map_page(collection_id, page, collection)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/lambda_function.py", line 78, in map_page
    vernacular_reader = import_vernacular_reader(
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/lambda_function.py", line 26, in import_vernacular_reader
    mapper_module = importlib.import_module(
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rikolti.metadata_mapper.mappers.pspl'
[2023-11-17, 17:06:46 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=validate_by_mapper_type, task_id=map_endpoint_task, execution_date=20231117T170606, start_date=20231117T170645, end_date=20231117T170646
[2023-11-17, 17:06:46 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 1990 for task map_endpoint_task (No module named 'rikolti.metadata_mapper.mappers.pspl'; 31734)
[2023-11-17, 17:06:46 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2023-11-17, 17:06:46 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check

```

**Comment by christinklez** [comment]
@amywieliczka @barbarahui -- unsure if there is a mapper naming issue happening here.

See Rikolti mapper name: https://registry.cdlib.org/admin/library_collection/collection/?rikolti_mapper_type=pspl.pspl

**Comment by amywieliczka** [comment]
This is totally a mapper naming issue. Adding it to my queue.

**Comment by amywieliczka** [comment]
Done! pspl_oai_dc should work now!

**Comment by christinklez** [comment]
@amywieliczka @barbarahui -- fails at `map_endpoint_task`; possibly an enrichment issue?

```
[2023-11-17, 19:59:13 UTC] {{logging_mixin.py:150}} INFO - 26715 : start mapping 2/8      
[2023-11-17, 19:59:13 UTC] {{logging_mixin.py:150}} INFO - ENRICHMENT ERROR: {}
[2023-11-17, 19:59:13 UTC] {{taskinstance.py:1824}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/utils_by_mapper_type.py", line 44, in map_endpoint_task
    mapper_job_results = map_endpoint(endpoint, limit)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/map_registry_collections.py", line 54, in map_endpoint
    map_result = lambda_shepherd.map_collection(
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/lambda_shepherd.py", line 119, in map_collection
    mapped_page = map_page(collection_id, page, collection)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/lambda_function.py", line 97, in map_page
    mapped_records = run_enrichments(
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/lambda_function.py", line 67, in run_enrichments
    records = [
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/lambda_function.py", line 68, in <listcomp>
    record.enrich(enrichment_func, **kwargs)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/mappers/mapper.py", line 210, in enrich
    raise e
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/mappers/mapper.py", line 207, in enrich
    return func(**kwargs)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/mappers/mapper.py", line 1038, in dedupe_sourceresource
    for key, value in self.mapped_data.items():
RuntimeError: dictionary changed size during iteration
[2023-11-17, 19:59:14 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=validate_by_mapper_type, task_id=map_endpoint_task, execution_date=20231117T170606, start_date=20231117T195912, end_date=20231117T195914
[2023-11-17, 19:59:14 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 2003 for task map_endpoint_task (dictionary changed size during iteration; 886)
[2023-11-17, 19:59:14 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2023-11-17, 19:59:14 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check

```

**Comment by barbarahui** [comment]
Fix: https://github.com/ucldc/rikolti/pull/647

**Comment by barbarahui** [comment]
@christinklez This should be fixed. Can you try running again?

**Comment by christinklez** [comment]
@barbarahui it works! Thank you so much!

**Comment by christinklez** [comment]
[2023-11-28, 19:05:56 UTC] {{python.py:183}} INFO - Done. Returned value was: [
'26707/vernacular_metadata_2023-11-28T19:05:35/mapped_metadata_2023-11-28T19:05:50/validation_2023-11-28T19:05:55.csv', 
'26715/vernacular_metadata_2023-11-28T19:05:36/mapped_metadata_2023-11-28T19:05:50/validation_2023-11-28T19:05:55.csv', 
'26716/vernacular_metadata_2023-11-28T19:05:37/mapped_metadata_2023-11-28T19:05:50/validation_2023-11-28T19:05:55.csv', 
'26717/vernacular_metadata_2023-11-28T19:05:38/mapped_metadata_2023-11-28T19:05:50/validation_2023-11-28T19:05:55.csv', 
'26718/vernacular_metadata_2023-11-28T19:05:39/mapped_metadata_2023-11-28T19:05:50/validation_2023-11-28T19:05:55.csv', 
'26719/vernacular_metadata_2023-11-28T19:05:39/mapped_metadata_2023-11-28T19:05:50/validation_2023-11-28T19:05:55.csv', 
'26720/vernacular_metadata_2023-11-28T19:05:40/mapped_metadata_2023-11-28T19:05:50/validation_2023-11-28T19:05:55.csv', 
'26721/vernacular_metadata_2023-11-28T19:05:41/mapped_metadata_2023-11-28T19:05:50/validation_2023-11-28T19:05:56.csv']

**Comment by christinklez** [comment]
Need to re-run this (hold for versioning fix): https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2023-11-17T17%3A06%3A06%2B00%3A00

**Comment by christinklez** [comment]
[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26707/vernacular_metadata_2023-11-28T22:29:23/mapped_metadata_2023-11-28T22:29:35/validation_2023-11-28T22:29:43.csv
[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#vernacular_metadata_2023-11-28T22:29:23/

[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26715/vernacular_metadata_2023-11-28T22:29:24/mapped_metadata_2023-11-28T22:29:36/validation_2023-11-28T22:29:43.csv
[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#vernacular_metadata_2023-11-28T22:29:24/

[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26716/vernacular_metadata_2023-11-28T22:29:25/mapped_metadata_2023-11-28T22:29:36/validation_2023-11-28T22:29:43.csv
[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#vernacular_metadata_2023-11-28T22:29:25/

[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26717/vernacular_metadata_2023-11-28T22:29:26/mapped_metadata_2023-11-28T22:29:36/validation_2023-11-28T22:29:44.csv
[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#vernacular_metadata_2023-11-28T22:29:26/

[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26718/vernacular_metadata_2023-11-28T22:29:27/mapped_metadata_2023-11-28T22:29:36/validation_2023-11-28T22:29:44.csv
[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#vernacular_metadata_2023-11-28T22:29:27/

[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26719/vernacular_metadata_2023-11-28T22:29:28/mapped_metadata_2023-11-28T22:29:37/validation_2023-11-28T22:29:44.csv
[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#vernacular_metadata_2023-11-28T22:29:28/

[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26720/vernacular_metadata_2023-11-28T22:29:29/mapped_metadata_2023-11-28T22:29:37/validation_2023-11-28T22:29:45.csv
[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#vernacular_metadata_2023-11-28T22:29:29/

[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26721/vernacular_metadata_2023-11-28T22:29:30/mapped_metadata_2023-11-28T22:29:37/validation_2023-11-28T22:29:45.csv
[2023-11-28, 22:29:45 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#vernacular_metadata_2023-11-28T22:29:30/

**Comment by christinklez** [comment]
[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26707/vernacular_metadata_2024-01-24T01:21:01/mapped_metadata_2024-01-24T01:21:14/validation_2024-01-24T01:21:22.csv
[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26707/vernacular_metadata_2024-01-24T01:21:01/mapped_metadata_2024-01-24T01:21:14/data/

[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26715/vernacular_metadata_2024-01-24T01:21:03/mapped_metadata_2024-01-24T01:21:14/validation_2024-01-24T01:21:22.csv
[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26715/vernacular_metadata_2024-01-24T01:21:03/mapped_metadata_2024-01-24T01:21:14/data/

[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26716/vernacular_metadata_2024-01-24T01:21:04/mapped_metadata_2024-01-24T01:21:15/validation_2024-01-24T01:21:22.csv
[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26716/vernacular_metadata_2024-01-24T01:21:04/mapped_metadata_2024-01-24T01:21:15/data/

[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26717/vernacular_metadata_2024-01-24T01:21:05/mapped_metadata_2024-01-24T01:21:15/validation_2024-01-24T01:21:23.csv
[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26717/vernacular_metadata_2024-01-24T01:21:05/mapped_metadata_2024-01-24T01:21:15/data/

[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26718/vernacular_metadata_2024-01-24T01:21:05/mapped_metadata_2024-01-24T01:21:15/validation_2024-01-24T01:21:23.csv
[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26718/vernacular_metadata_2024-01-24T01:21:05/mapped_metadata_2024-01-24T01:21:15/data/

[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26719/vernacular_metadata_2024-01-24T01:21:06/mapped_metadata_2024-01-24T01:21:16/validation_2024-01-24T01:21:23.csv
[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26719/vernacular_metadata_2024-01-24T01:21:06/mapped_metadata_2024-01-24T01:21:16/data/

[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26720/vernacular_metadata_2024-01-24T01:21:07/mapped_metadata_2024-01-24T01:21:16/validation_2024-01-24T01:21:24.csv
[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26720/vernacular_metadata_2024-01-24T01:21:07/mapped_metadata_2024-01-24T01:21:16/data/

[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26721/vernacular_metadata_2024-01-24T01:21:08/mapped_metadata_2024-01-24T01:21:16/validation_2024-01-24T01:21:24.csv
[2024-01-24, 01:21:24 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26721/vernacular_metadata_2024-01-24T01:21:08/mapped_metadata_2024-01-24T01:21:16/data/

**Comment by christinklez** [comment]
[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26707/vernacular_metadata_2024-02-01T17:17:35/mapped_metadata_2024-02-01T17:17:50/validation_2024-02-01T17:17:57.csv
[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26707/vernacular_metadata_2024-02-01T17:17:35/mapped_metadata_2024-02-01T17:17:50/data/

[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26715/vernacular_metadata_2024-02-01T17:17:37/mapped_metadata_2024-02-01T17:17:50/validation_2024-02-01T17:17:57.csv
[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26715/vernacular_metadata_2024-02-01T17:17:37/mapped_metadata_2024-02-01T17:17:50/data/

[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26716/vernacular_metadata_2024-02-01T17:17:38/mapped_metadata_2024-02-01T17:17:50/validation_2024-02-01T17:17:58.csv
[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26716/vernacular_metadata_2024-02-01T17:17:38/mapped_metadata_2024-02-01T17:17:50/data/

[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26717/vernacular_metadata_2024-02-01T17:17:38/mapped_metadata_2024-02-01T17:17:51/validation_2024-02-01T17:17:58.csv
[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26717/vernacular_metadata_2024-02-01T17:17:38/mapped_metadata_2024-02-01T17:17:51/data/

[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26718/vernacular_metadata_2024-02-01T17:17:39/mapped_metadata_2024-02-01T17:17:51/validation_2024-02-01T17:17:59.csv
[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26718/vernacular_metadata_2024-02-01T17:17:39/mapped_metadata_2024-02-01T17:17:51/data/

[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26719/vernacular_metadata_2024-02-01T17:17:40/mapped_metadata_2024-02-01T17:17:51/validation_2024-02-01T17:17:59.csv
[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26719/vernacular_metadata_2024-02-01T17:17:40/mapped_metadata_2024-02-01T17:17:51/data/

[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26720/vernacular_metadata_2024-02-01T17:17:41/mapped_metadata_2024-02-01T17:17:51/validation_2024-02-01T17:17:59.csv
[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26720/vernacular_metadata_2024-02-01T17:17:41/mapped_metadata_2024-02-01T17:17:51/data/

[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26721/vernacular_metadata_2024-02-01T17:17:42/mapped_metadata_2024-02-01T17:17:52/validation_2024-02-01T17:18:00.csv
[2024-02-01, 17:18:00 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26721/vernacular_metadata_2024-02-01T17:17:42/mapped_metadata_2024-02-01T17:17:52/data/

**Comment by christinklez** [comment]
Accepted on 2024, Feb 2!
