### ISSUE TITLE
Generate and review validation reports: csu_sac_oai_dc -- post-mvp fixes

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#642]
- **Step 2: Generate reports** [status: in progress --> ready for review]
  - [x] Generate validation reports (run `validate_by_mapper DAG`): https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/validate_by_mapper_type/grid?dag_run_id=manual__2024-11-04T23%3A48%3A08%2B00%3A00&num_runs=50&tab=details&base_date=2024-11-04T23%3A48%3A08%2B00%3A00
  - [x] Add a comment (in this issue) to the output URLs
  - [x] Download the validation reports locally; prepend the collection registry number to the filename
  - [x] Upload validation reports to the [Rikolti Data Validation](https://drive.google.com/drive/folders/1AgDPsz6oyDhsfgRuLyjomaXYgE1sPLNT) folder
- **Step 3: Review reports**  [status: ready for review --> review in progress]
  - [x] Review [sample collections validation reports](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1143782640); leave notes in the spreadsheet
  - [x] Quickly (and not very deeply) scan through other validation reports (to identify if any new metadata fields surface)
  - [x] Synthesize notes at the [mapper level](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1100474517)
  - [x] Share an update (and surface any anomalies) during a weekly check-in (Mondays at 3:00pm)
- **Step 4: Have data validation issues? Address & resolve validation issues (synthesized mapper-level):**
  - [ ] Create a new issue (“Validation results: Rikolti mapper name“) and report/request CIC fixes & investigations. Assign to CIC.
  - [ ] Add a comment to link to the new “validation results” issue.
  - [ ] Add a “blocked/paused” label to this issue. Include a status note in this issue title (e,g., HOLD for CIC fixes; HOLD for code review; etc.) 
  - [ ] Move this issue back to the “To Do” pile.
- [Re-generate & re-review (repeat steps 2-3 above, as needed.]
- **Step 5: Have acceptable validation reports?**
  - [x] Move the valid (accepted) reports to the “VALID” folder in google drive.
  - [x] Update the [mapper progress spreadsheet](https://docs.google.com/spreadsheets/d/1XkBwi8jiuGgrWvQBqjkrbavSl13yyrQNyRyEb_CQ4z0/edit#gid=1100474517); indicate that the mapper is accepted

**Comment by christinklez** [comment]
Fails at `validate_endpoint_task`: 

```
[2023-11-20, 21:58:33 UTC] {{logging_mixin.py:150}} INFO - 26723  Validating collection
[2023-11-20, 21:58:34 UTC] {{taskinstance.py:1824}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/utils_by_mapper_type.py", line 70, in validate_endpoint_task
    num_rows, file_location = create_collection_validation_csv(
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 113, in create_collection_validation_csv
    result = validate_collection(collection_id, **options)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 53, in validate_collection
    validate_page(collection_id, page_id, validator)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 84, in validate_page
    get_comparison_data(collection_id,
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 125, in get_comparison_data
    solr_data = get_solr_data(collection_id, harvest_ids)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 144, in get_solr_data
    response = make_solr_request(**query)
  File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 157, in make_solr_request
    res.raise_for_status()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://solr.calisphere.org/solr/query/
[2023-11-20, 21:58:34 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=validate_by_mapper_type, task_id=validate_endpoint_task, execution_date=20231120T214747, start_date=20231120T215829, end_date=20231120T215834
[2023-11-20, 21:58:34 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 2024 for task validate_endpoint_task (400 Client Error: Bad Request for url: https://solr.calisphere.org/solr/query/; 7691)
[2023-11-20, 21:58:34 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2023-11-20, 21:58:34 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by barbarahui** [comment]
Fix: https://github.com/ucldc/rikolti/pull/650

**Comment by barbarahui** [comment]
@christinklez This should be fixed. Can you try running again?

**Comment by christinklez** [comment]
@barbarahui this runs! Thank you!

**Comment by barbarahui** [comment]
@christinklez This should be fixed. Can you try running it again? If it works, then this should fix the others with the same error.

**Comment by christinklez** [comment]
@barbarahui that works, thank you so much! I'll run the others as well!

**Comment by christinklez** [comment]
[2023-11-29, 23:27:45 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/11068/vernacular_metadata_2023-11-29T00:14:26/mapped_metadata_2023-11-29T00:15:10/validation_2023-11-29T23:27:43.csv
[2023-11-29, 23:27:45 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://{bucket}.s3.us-west-2.amazonaws.com/index.html#11068/vernacular_metadata_2023-11-29T00:14:26/mapped_metadata_2023-11-29T00:15:10/data/


[2023-11-29, 23:27:45 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26723/vernacular_metadata_2023-11-29T00:14:57/mapped_metadata_2023-11-29T00:21:50/validation_2023-11-29T23:27:44.csv
[2023-11-29, 23:27:45 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://{bucket}.s3.us-west-2.amazonaws.com/index.html#26723/vernacular_metadata_2023-11-29T00:14:57/mapped_metadata_2023-11-29T00:21:50/data/


[2023-11-29, 23:27:45 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27968/vernacular_metadata_2023-11-29T00:15:00/mapped_metadata_2023-11-29T00:21:59/validation_2023-11-29T23:27:45.csv
[2023-11-29, 23:27:45 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://{bucket}.s3.us-west-2.amazonaws.com/index.html#27968/vernacular_metadata_2023-11-29T00:15:00/mapped_metadata_2023-11-29T00:21:59/data/

**Comment by christinklez** [comment]
Validation fixes requested: https://github.com/ucldc/rikolti/issues/664

**Comment by christinklez** [comment]
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/11068/vernacular_metadata_2024-01-25T20:53:06/mapped_metadata_2024-01-25T20:53:50/validation_2024-01-25T21:02:47.csv
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#11068/vernacular_metadata_2024-01-25T20:53:06/mapped_metadata_2024-01-25T20:53:50/data/

[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27968/vernacular_metadata_2024-01-25T20:53:38/mapped_metadata_2024-01-25T21:01:14/validation_2024-01-25T21:02:48.csv
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27968/vernacular_metadata_2024-01-25T20:53:38/mapped_metadata_2024-01-25T21:01:14/data/

```
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} WARNING - ------------------------------------------------------------
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} WARNING - -------------------- Validation Errors ---------------------
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} WARNING - ------------------------------------------------------------
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} WARNING -  Collection 26723: No mapped metadata found for 26723 page 26723/vernacular_metadata_2024-01-25T20:53:33/mapped_metadata_2024-01-25T21:01:06/data/0.jsonl. Aborting. 
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} WARNING - Traceback (most recent call last):
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} WARNING -   File "/usr/local/airflow/dags/rikolti/dags/utils_by_mapper_type.py", line 171, in validate_endpoint_task
    num_rows, version_page = create_collection_validation_csv(
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 217, in create_collection_validation_csv
    result = validate_collection(collection_id, mapped_page_paths, **options)
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 66, in validate_collection
    rikolti_ids, new_ids = validate_page(collection_id, page_path, validator)
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} WARNING -   File "/usr/local/airflow/dags/rikolti/metadata_mapper/validate_mapping.py", line 171, in validate_page
    raise ValueError(
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} WARNING - ValueError: No mapped metadata found for 26723 page 26723/vernacular_metadata_2024-01-25T20:53:33/mapped_metadata_2024-01-25T21:01:06/data/0.jsonl. Aborting.
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} WARNING - <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} INFO - ************************************************************
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} INFO - 1 collections encountered validation errors
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} INFO - please validate manually: [26723]
[2024-01-25, 21:02:49 UTC] {{logging_mixin.py:150}} INFO - ************************************************************
```

**Comment by christinklez** [comment]
[2024-02-03, 00:07:00 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/11068/vernacular_metadata_2024-02-02T23:57:25/mapped_metadata_2024-02-02T23:58:03/validation_2024-02-03T00:06:58.csv
[2024-02-03, 00:07:00 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#11068/vernacular_metadata_2024-02-02T23:57:25/mapped_metadata_2024-02-02T23:58:03/data/

[2024-02-03, 00:07:00 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26723/vernacular_metadata_2024-02-02T23:57:48/mapped_metadata_2024-02-03T00:05:19/validation_2024-02-03T00:06:59.csv
[2024-02-03, 00:07:00 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26723/vernacular_metadata_2024-02-02T23:57:48/mapped_metadata_2024-02-03T00:05:19/data/

[2024-02-03, 00:07:00 UTC] {{logging_mixin.py:150}} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27968/vernacular_metadata_2024-02-02T23:57:52/mapped_metadata_2024-02-03T00:05:27/validation_2024-02-03T00:07:00.csv
[2024-02-03, 00:07:00 UTC] {{logging_mixin.py:150}} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27968/vernacular_metadata_2024-02-02T23:57:52/mapped_metadata_2024-02-03T00:05:27/data/

**Comment by christinklez** [comment]
[2024-11-04, 23:59:46 UTC] {logging_mixin.py:188} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/11068/vernacular_metadata_2024-11-04T23:48:18/mapped_metadata_2024-11-04T23:48:55/validation_2024-11-04T23:59:44.csv
[2024-11-04, 23:59:46 UTC] {logging_mixin.py:188} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#11068/vernacular_metadata_2024-11-04T23:48:18/mapped_metadata_2024-11-04T23:48:55/data/
[2024-11-04, 23:59:46 UTC] {logging_mixin.py:188} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26723/vernacular_metadata_2024-11-04T23:48:41/mapped_metadata_2024-11-04T23:57:07/validation_2024-11-04T23:59:45.csv
[2024-11-04, 23:59:46 UTC] {logging_mixin.py:188} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26723/vernacular_metadata_2024-11-04T23:48:41/mapped_metadata_2024-11-04T23:57:07/data/
[2024-11-04, 23:59:46 UTC] {logging_mixin.py:188} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27968/vernacular_metadata_2024-11-04T23:48:47/mapped_metadata_2024-11-04T23:58:03/validation_2024-11-04T23:59:46.csv
[2024-11-04, 23:59:46 UTC] {logging_mixin.py:188} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27968/vernacular_metadata_2024-11-04T23:48:47/mapped_metadata_2024-11-04T23:58:03/data/

**Comment by christinklez** [comment]
[2024-11-05, 19:38:29 UTC] {logging_mixin.py:188} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/11068/vernacular_metadata_2024-11-05T19:27:10/mapped_metadata_2024-11-05T19:27:48/validation_2024-11-05T19:38:27.csv
[2024-11-05, 19:38:29 UTC] {logging_mixin.py:188} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#11068/vernacular_metadata_2024-11-05T19:27:10/mapped_metadata_2024-11-05T19:27:48/data/

[2024-11-05, 19:38:29 UTC] {logging_mixin.py:188} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/26723/vernacular_metadata_2024-11-05T19:27:33/mapped_metadata_2024-11-05T19:35:51/validation_2024-11-05T19:38:28.csv
[2024-11-05, 19:38:29 UTC] {logging_mixin.py:188} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#26723/vernacular_metadata_2024-11-05T19:27:33/mapped_metadata_2024-11-05T19:35:51/data/

[2024-11-05, 19:38:29 UTC] {logging_mixin.py:188} INFO - Download validation report at: https://rikolti-data.s3.amazonaws.com/27968/vernacular_metadata_2024-11-05T19:27:39/mapped_metadata_2024-11-05T19:36:50/validation_2024-11-05T19:38:29.csv
[2024-11-05, 19:38:29 UTC] {logging_mixin.py:188} INFO - Review collection data at: https://rikolti-data.s3.us-west-2.amazonaws.com/index.html#27968/vernacular_metadata_2024-11-05T19:27:39/mapped_metadata_2024-11-05T19:36:50/data/
