### ISSUE TITLE
[bug] `merge_any_child_records` error (4 Nuxeo collections)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#806]
First want to note that I was able to run two Nuxeo collections that did pass through the `merge_any_child_records` task ([28197](https://calisphere-stage.cdlib.org/collections/28197/) & [28199](https://calisphere-stage.cdlib.org/collections/28199/)), both of which came through to -stage as merged complex sets (although not quite displaying as such due to object viewer issues).

- [ ] [Log for 28200](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-12T19%3A52%3A55%2B00%3A00&num_runs=100&task_id=merge_any_child_records&tab=logs) - [permanent link to merge_any_child_records](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=merge_any_child_records&execution_date=2024-03-12T19%3A52%3A55%2B00%3A00)
   - Run ID: manual__2024-03-12T19:52:55+00:00
   - I couldn't tell if there's a particular Nuxeo record that's error'ing out.
Link to Nuxeo folder: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/bea14da4-03d0-408b-a1e4-0d7de66d2a30/view_documents
- [ ] [Log for 28012](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-12T22%3A40%3A31%2B00%3A00&num_runs=100&task_id=merge_any_child_records&tab=mapped_tasks) - [permanent link to merge_any_child_records](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=merge_any_child_records&execution_date=2024-03-12T22%3A40%3A31%2B00%3A00)
   - Run ID: manual__2024-03-12T22:40:31+00:00
- [ ] [Log for 28204](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-12T23%3A25%3A47%2B00%3A00&num_runs=100&task_id=merge_any_child_records&tab=logs) - [permanent link to merge_any_child_records](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=merge_any_child_records&execution_date=2024-03-12T23%3A25%3A47%2B00%3A00)
   - Run ID: manual__2024-03-12T23:25:47+00:00
- [ ] [Log for 28205](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-12T23%3A26%3A04%2B00%3A00&num_runs=100&task_id=merge_any_child_records&tab=logs) - [permanent link to merge_any_child_records](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=merge_any_child_records&execution_date=2024-03-12T23%3A26%3A04%2B00%3A00)
   - Run ID: manual__2024-03-12T23:26:04+00:00

Traceback error for 28200:
```
[2024-03-12, 20:06:47 UTC] {{taskinstance.py:1824}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/harvest_dag.py", line 44, in merge_any_child_records_task
    child_directories = get_child_directories(version)
  File "/usr/local/airflow/dags/rikolti/utils/versions.py", line 197, in get_child_directories
    child_directories = storage.list_dirs(
  File "/usr/local/airflow/dags/rikolti/utils/storage.py", line 49, in list_dirs
    for obj in s3_objects['CommonPrefixes']
KeyError: 'CommonPrefixes'
[2024-03-12, 20:06:47 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=merge_any_child_records, execution_date=20240312T195255, start_date=20240312T200646, end_date=20240312T200647
[2024-03-12, 20:06:47 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: e530379a-c70a-5b71-952d-69f07f1d3165
[2024-03-12, 20:06:47 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 17067 for task merge_any_child_records ('CommonPrefixes'; 29614)
[2024-03-12, 20:06:47 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2024-03-12, 20:06:47 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check

```

**Comment by amywieliczka** [comment]
Fixed! I also re-ran `merge_any_child_records` and `create_stage_index` tasks for the 4 collections linked above!
