### ISSUE TITLE
[bug] `merge_any_child_records` error (4 non-Nuxeo collections)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#808]
Non-Nuxeo collections are error'ing out during the `merge_any_child_records` task. 

- [ ] [Log for 28206](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-12T23%3A34%3A08%2B00%3A00&num_runs=100&task_id=merge_any_child_records&tab=logs) (mapper: ucsd_blacklight) - [permanent link to merge_any_child_records](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=merge_any_child_records&execution_date=2024-03-12T23%3A34%3A08%2B00%3A00)
   - Run ID: manual__2024-03-12T23:34:08+00:00
- [ ] [Log for 28207](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-12T23%3A34%3A26%2B00%3A00&num_runs=100&task_id=merge_any_child_records&tab=logs) (mapper: ucsd_blacklight) - [permanent link to merge_any_child_records](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=merge_any_child_records&execution_date=2024-03-12T23%3A34%3A26%2B00%3A00)
   - Run ID: manual__2024-03-12T23:34:26+00:00
- [ ] [Log for 28208](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-12T23%3A38%3A18%2B00%3A00&num_runs=100&task_id=merge_any_child_records&tab=logs) (mapper: ucsd_blacklight) - [permanent link to merge_any_child_records](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=merge_any_child_records&execution_date=2024-03-12T23%3A38%3A18%2B00%3A00)
   - Run ID: manual__2024-03-12T23:38:18+00:00
   - Note that 28208 previously harvested to -stage and a preview is still available: https://calisphere-stage.cdlib.org/collections/28208/
- [ ] [Log for 27305](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-03-12T23%3A42%3A34%2B00%3A00&num_runs=100&tab=logs&task_id=merge_any_child_records) (mapper: oai.tv_academy) - [permanent link to merge_any_child_records](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=merge_any_child_records&execution_date=2024-03-12T23%3A42%3A34%2B00%3A00)
   - Run ID: manual__2024-03-12T23:42:34+00:00
   - Note that 27305 previously harvested to -stage and a preview is still available: https://calisphere-stage.cdlib.org/collections/27305/
   - Also, this round had an error during validation as well - [permanent link to validate_collection](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=mapping.validate_collection&execution_date=2024-03-12T23%3A42%3A34%2B00%3A00)

Traceback for 28206:
```
[2024-03-12, 23:38:40 UTC] {{taskinstance.py:1824}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/harvest_dag.py", line 44, in merge_any_child_records_task
    child_directories = get_child_directories(version)
  File "/usr/local/airflow/dags/rikolti/utils/versions.py", line 197, in get_child_directories
    child_directories = storage.list_dirs(
  File "/usr/local/airflow/dags/rikolti/utils/storage.py", line 49, in list_dirs
    for obj in s3_objects['CommonPrefixes']
KeyError: 'CommonPrefixes'
[2024-03-12, 23:38:40 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=merge_any_child_records, execution_date=20240312T233408, start_date=20240312T233839, end_date=20240312T233840
[2024-03-12, 23:38:40 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: ec7915ca-491a-5482-8611-4ba0a0da5e0d
[2024-03-12, 23:38:40 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 17964 for task merge_any_child_records ('CommonPrefixes'; 2091)
[2024-03-12, 23:38:40 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2024-03-12, 23:38:40 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check

```

**Comment by amywieliczka** [comment]
This should be fixed as well - re-running the 4 collections now!

**Comment by amywieliczka** [comment]
Confirmed fixed!
