### ISSUE TITLE
[file format issue] `content harvest` error for a Nuxeo collection: `UnsupportedMimetype: Mime-type 'application/photoshop' was unrecognized.` - contacted UCI

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#889]
Contacted UCI: https://help.oac.cdlib.org/a/tickets/137544 -- UCI is working on transforming the PSDs into jpg/tif.

***

2 PSD (mimetype application/photoshop) records result in a content harvesting error:

Mapper: Nuxeo
Registry ID: 38

## These objects are triggering the error
(See mapped metadata details at the bottom of the page.)
- https://nuxeo.cdlib.org/nuxeo/nxdoc/default/fc3e4ff8-536a-4758-8345-7820003e39c6/view_documents 
   - https://calisphere.org/item/fc3e4ff8-536a-4758-8345-7820003e39c6 (does not exist)

- https://nuxeo.cdlib.org/nuxeo/nxdoc/default/7966bef0-3106-4fa5-8e95-590120d73b23/view_documents
   - https://calisphere.org/item/7966bef0-3106-4fa5-8e95-590120d73b23 (does not exist)

It seems that the legacy harvester skipped these items previously.

## Harvesting logs
- Content harvest page 28
- Link to Airflow gridview: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-04-24T19%3A56%3A49%2B00%3A00&num_runs=365&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=28
- Permalink to the log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-24T19%3A56%3A49%2B00%3A00&map_index=28

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 71, in harvest_record_content
    check_media_mimetype(media.src_mime_type)
  File "/content_harvester/content_types.py", line 59, in check_media_mimetype
    raise UnsupportedMimetype(
content_harvester.content_types.UnsupportedMimetype: Mime-type 'application/photoshop' was unrecognized. We don't know how to deal with this

```

## From the mapped metadata file

```
{"calisphere-id": "fc3e4ff8-536a-4758-8345-7820003e39c6", "campus_data": ["3::UC Irvine"], "campus_name": ["UC Irvine"], "campus_url": ["3"], "collection_data": ["38::Cancian (Frank) Photographs for Main Street UCI"], "collection_name": ["Cancian (Frank) Photographs for Main Street UCI"], "collection_url": ["38"], "creator": ["Cancian, Frank"], "date": ["2010-05-13T12:11:09-07:00"], "description": ["Scope/Content: Students and community members of differing backgrounds come together to share their views on Israel and Palestine at the \"Palestine Awareness Week\" event sponsored by the Muslim Student Union.", "Scope/Content: Frank Cancian Photographs for Main Street UCI. AS-154. Special Collections and Archives, The UC Irvine Libraries, Irvine, California."], "fetcher_type": ["nuxeo"], "id": "ark:/81235/d81t28", "identifier": ["ark:/81235/d81t28", "http://hdl.handle.net/10575/3726"], "is_shown_at": "https://calisphere.org/item/fc3e4ff8-536a-4758-8345-7820003e39c6", "is_shown_by": {"url": "https://nuxeo.cdlib.org/nuxeo/nxfile/default/fc3e4ff8-536a-4758-8345-7820003e39c6/picture:views/2/content/Medium_I513-83aa.jpg?changeToken=9-0", "mimetype": "image/jpeg", "filename": "Medium_I513-83aa.jpg", "nuxeo_type": "SampleCustomPicture"}, "item_count": 0, "language": ["English", "eng"], "mapper_type": ["nuxeo.nuxeo"], "media_source": {"url": "https://nuxeo.cdlib.org/nuxeo/nxfile/default/fc3e4ff8-536a-4758-8345-7820003e39c6/file:content/I513-83aa.psd?changeToken=9-0", "mimetype": "application/photoshop", "filename": "I513-83aa.psd", "nuxeo_type": "SampleCustomPicture"}, "relation": ["Frank Cancian photographs for Main Street UCI, 2010"], "repository_data": ["17::Libraries, University Archives::UC Irvine"], "repository_name": ["Libraries, University Archives"], "repository_url": ["17"], "rights": ["Copyrighted", "This material is provided for private study, scholarship, or research. Transmission or reproduction of any material protected by copyright beyond that allowed by fair use requires the written permission of the copyright owners. The authors or their heirs retain their copyrights to the material. Contact the University of California, Irvine Libraries, Special Collections and Archives for more information (spcoll@uci.edu)."], "sort_collection_data": ["cancian frank photographs for main street uci::Cancian (Frank) Photographs for Main Street UCI::38"], "sort_title": "proisraeli and propeace supporters protesting palestine awareness event on the ring mall photograph at university of california irvine", "subject": ["Political activities and groups", "Protests and demonstrations", "Religious activities and groups", "Students"], "thumbnail_source": {"url": "https://nuxeo.cdlib.org/nuxeo/nxfile/default/fc3e4ff8-536a-4758-8345-7820003e39c6/picture:views/2/content/Medium_I513-83aa.jpg?changeToken=9-0", "mimetype": "image/jpeg", "filename": "Medium_I513-83aa.jpg", "nuxeo_type": "SampleCustomPicture"}, "title": ["Pro-Israeli and Pro-Peace supporters protesting Palestine Awareness event on the Ring Mall; photograph at University of California, Irvine"], "type": ["image"], "url_item": "https://calisphere.org/item/fc3e4ff8-536a-4758-8345-7820003e39c6"}, 

{"calisphere-id": "7966bef0-3106-4fa5-8e95-590120d73b23", "campus_data": ["3::UC Irvine"], "campus_name": ["UC Irvine"], "campus_url": ["3"], "collection_data": ["38::Cancian (Frank) Photographs for Main Street UCI"], "collection_name": ["Cancian (Frank) Photographs for Main Street UCI"], "collection_url": ["38"], "creator": ["Cancian, Frank"], "date": ["2010-05-13T12:11:09-07:00"], "description": ["Scope/Content: Students and community members of differing backgrounds come together to share their views on Israel and Palestine at the \"Palestine Awareness Week\" event sponsored by the Muslim Student Union.", "Scope/Content: Frank Cancian Photographs for Main Street UCI. AS-154. Special Collections and Archives, The UC Irvine Libraries, Irvine, California."], "fetcher_type": ["nuxeo"], "id": "ark:/81235/d8x111", "identifier": ["ark:/81235/d8x111", "http://hdl.handle.net/10575/3727"], "is_shown_at": "https://calisphere.org/item/7966bef0-3106-4fa5-8e95-590120d73b23", "is_shown_by": {"url": "https://nuxeo.cdlib.org/nuxeo/nxfile/default/7966bef0-3106-4fa5-8e95-590120d73b23/picture:views/2/content/Medium_I513-83ab.jpg?changeToken=9-0", "mimetype": "image/jpeg", "filename": "Medium_I513-83ab.jpg", "nuxeo_type": "SampleCustomPicture"}, "item_count": 0, "language": ["English", "eng"], "mapper_type": ["nuxeo.nuxeo"], "media_source": {"url": "https://nuxeo.cdlib.org/nuxeo/nxfile/default/7966bef0-3106-4fa5-8e95-590120d73b23/file:content/I513-83ab.psd?changeToken=9-0", "mimetype": "application/photoshop", "filename": "I513-83ab.psd", "nuxeo_type": "SampleCustomPicture"}, "relation": ["Frank Cancian photographs for Main Street UCI, 2010"], "repository_data": ["17::Libraries, University Archives::UC Irvine"], "repository_name": ["Libraries, University Archives"], "repository_url": ["17"], "rights": ["Copyrighted", "This material is provided for private study, scholarship, or research. Transmission or reproduction of any material protected by copyright beyond that allowed by fair use requires the written permission of the copyright owners. The authors or their heirs retain their copyrights to the material. Contact the University of California, Irvine Libraries, Special Collections and Archives for more information (spcoll@uci.edu)."], "sort_collection_data": ["cancian frank photographs for main street uci::Cancian (Frank) Photographs for Main Street UCI::38"], "sort_title": "proisraeli and propeace supporters protesting palestine awareness event on the ring mall photograph at university of california irvine", "subject": ["Political activities and groups", "Protests and demonstrations", "Religious activities and groups", "Students"], "thumbnail_source": {"url": "https://nuxeo.cdlib.org/nuxeo/nxfile/default/7966bef0-3106-4fa5-8e95-590120d73b23/picture:views/2/content/Medium_I513-83ab.jpg?changeToken=9-0", "mimetype": "image/jpeg", "filename": "Medium_I513-83ab.jpg", "nuxeo_type": "SampleCustomPicture"}, "title": ["Pro-Israeli and Pro-Peace supporters protesting Palestine Awareness event on the Ring Mall; photograph at University of California, Irvine"], "type": ["image"], "url_item": "https://calisphere.org/item/7966bef0-3106-4fa5-8e95-590120d73b23"}, 
```

**Comment by christinklez** [comment]
I will contact UCI to let them know about these two objects. I'll ask them to swap the two PSD files in the "Main File" with a JPG (or such) file. If they're unable to get to this, I'll ask them to place these records in separate "publish" & "do not publish" folder.

Something we should discuss later is whether we want the harvester to skip records that it doesn't know how to deal with.

**Comment by christinklez** [comment]
@aturner just noticed that on our Nuxeo FD doc, it actually seems to indicate that PSD is okay (in the image section): https://help.oac.cdlib.org/support/solutions/articles/9000100797-creating-objects/

The PSD objects seem to have skipped over in the legacy harvester.
@barbarahui do you happen to know if PSD image format is something Rikolti is able to support? Let us know if this is at least technically feasible (either now or down the line).
@aturner let's strategize how to update our documentation on the PSD filetypes.

**Comment by christinklez** [comment]
Discussed that @barbarahui will test if PSD can be defined as a mimetype; this would ideally result in converting to a JPG.

**Comment by barbarahui** [comment]
Actually after having read about PSD files a bit, I don't think it makes sense for Calisphere to support them. Can you ask UCI to upload a jpg?

**Comment by christinklez** [comment]
Thanks @barbarahui! I'll ask them to swap out the image with a jpg or tif.

I think we should also update our documentation, along the lines of Nuxeo supporting PSD, but is not a supported Calisphere harvesting format. Probably AI files as well, I assume.

**Comment by christinklez** [comment]
@aturner Suggested edits on the freshdesk page: https://help.oac.cdlib.org/support/solutions/articles/9000100797-creating-objects/preview -- it's saved, but not yet published. Please feel free to preview & tweak! Thanks!

**Comment by aturner** [comment]
Thanks @christinklez -- incorporated some wordsmithing edits, and published!

**Comment by christinklez** [comment]
Thank you so much, @aturner! I'll ask UCI if they can swap out the image formats for these two records.

**Comment by christinklez** [comment]
UCI swapped out these PSD images with JPGs. The collection did pass through the `content harvest` task, and awaiting to go through the `create_stage_index` task, which we will re-run when the shard issue is resolved. Closing this issue out.
