### ISSUE TITLE
[filename error] Nuxeo content harvest `ERROR: no thumbnail found for Nonerecord ac9c3d42-d465-4196-a5d5-c503afdc1f8d` - contacted UCI

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#891]
This log includes a warning and an error. (I assume the warning is okay, but just want to double check.) 
Possibly an issue with MOV formats?

Registry ID: 26711
- Mapper: Nuxeo
- Nuxeo project folder: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/a1dc09e2-4d2a-4995-b799-f9038eb16f43/view_documents
- Error: ac9c3d42-d465-4196-a5d5-c503afdc1f8d
   - Title: AS-081-72-A.mov
   - Nuxeo record:  https://nuxeo.cdlib.org/nuxeo/nxdoc/default/ac9c3d42-d465-4196-a5d5-c503afdc1f8d/view_documents
   - NOT in Calisphere production: https://calisphere.org/item/ac9c3d42-d465-4196-a5d5-c503afdc1f8d/
- Warning: 275428b8-6260-4fb8-93f7-0f431e70b59d
   - Title: UC Regents Meeting, Chancellor Laurel L. Wilkening's Remarks
   - Nuxeo record:  https://nuxeo.cdlib.org/nuxeo/nxdoc/default/275428b8-6260-4fb8-93f7-0f431e70b59d/view_documents
   - In Calisphere production: https://calisphere.org/item/ark:/81235/d8f26x/

Run ID: manual__2024-04-24T22:02:20+00:00
- Error during the content harvest task, mapped page 0
- Airflow gridview: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=365&dag_run_id=manual__2024-04-24T22%3A02%3A20%2B00%3A00&task_id=content_harvesting.content_harvest&tab=mapped_tasks
- Permalink to log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-24T22%3A02%3A20%2B00%3A00&map_index=0

## Content Harvest task mapped page 0 error log:
```
[2024-04-25, 00:11:37 UTC] {{ecs.py:619}} INFO - ECS Task stopped, check status: {'tasks': [{'attachments': [{'id': '9e3bcbea-6c00-4963-99c1-efed45681964', 'type': 'ElasticNetworkInterface', 'status': 'DELETED', 'details': [{'name': 'subnetId', 'value': 'subnet-09e65806b80ebad6b'}, {'name': 'networkInterfaceId', 'value': 'eni-0567c6387632075b3'}, {'name': 'macAddress', 'value': '02:72:5c:f0:21:61'}, {'name': 'privateDnsName', 'value': 'ip-10-192-21-253.us-west-2.compute.internal'}, {'name': 'privateIPv4Address', 'value': '10.192.21.253'}]}], 'attributes': [{'name': 'ecs.cpu-architecture', 'value': 'x86_64'}], 'availabilityZone': 'us-west-2b', 'clusterArn': 'arn:aws:ecs:us-west-2:777968769372:cluster/rikolti-ecs-cluster', 'connectivity': 'CONNECTED', 'connectivityAt': datetime.datetime(2024, 4, 24, 23, 53, 10, 4000, tzinfo=tzlocal()), 'containers': [{'containerArn': 'arn:aws:ecs:us-west-2:777968769372:container/rikolti-ecs-cluster/ab29a84203c94508bc12408f8f689496/104298c7-6e9a-484a-89b4-ff490ee10744', 'taskArn': 'arn:aws:ecs:us-west-2:777968769372:task/rikolti-ecs-cluster/ab29a84203c94508bc12408f8f689496', 'name': 'rikolti-content_harvester', 'image': 'public.ecr.aws/b6c7x7s4/rikolti/content_harvester:latest', 'imageDigest': 'sha256:21540e4534d28e86ffc9154442e1444d54cb2a2071ce13865c16eb7f1a19dc36', 'runtimeId': 'ab29a84203c94508bc12408f8f689496-3530892436', 'lastStatus': 'STOPPED', 'exitCode': 1, 'networkBindings': [], 'networkInterfaces': [{'attachmentId': '9e3bcbea-6c00-4963-99c1-efed45681964', 'privateIpv4Address': '10.192.21.253'}], 'healthStatus': 'UNKNOWN', 'cpu': '0'}], 'cpu': '1024', 'createdAt': datetime.datetime(2024, 4, 24, 23, 53, 4, 818000, tzinfo=tzlocal()), 'desiredStatus': 'STOPPED', 'enableExecuteCommand': False, 'executionStoppedAt': datetime.datetime(2024, 4, 25, 0, 10, 48, 194000, tzinfo=tzlocal()), 'group': 'family:rikolti-content_harvester-task-definition', 'healthStatus': 'UNKNOWN', 'lastStatus': 'STOPPED', 'launchType': 'FARGATE', 'memory': '3072', 'overrides': {'containerOverrides': [{'name': 'rikolti-content_harvester', 'command': ['26711', '["26711/vernacular_metadata_2024-04-24T22:02:32/mapped_metadata_2024-04-24T22:02:49/data/r-p0.jsonl"]', '26711/vernacular_metadata_2024-04-24T22:02:32/mapped_metadata_2024-04-24T22:02:49/with_content_urls_2024-04-24T22:03:26/', 'nuxeo.nuxeo'], 'environment': [{'name': 'MAPPED_DATA', 'value': 's3://rikolti-data'}, {'name': 'WITH_CONTENT_URL_DATA', 'value': 's3://rikolti-data'}, {'name': 'CONTENT_ROOT', 'value': 's3://rikolti-content'}, {'name': 'NUXEO_USER', 'value': 'Administrator'}, {'name': 'NUXEO_PASS', 'value': 'cable8:ringmasters'}, {'name': 'AWS_RETRY_MODE', 'value': 'standard'}, {'name': 'AWS_MAX_ATTEMPTS', 'value': '10'}]}], 'inferenceAcceleratorOverrides': []}, 'platformVersion': '1.4.0', 'platformFamily': 'Linux', 'pullStartedAt': datetime.datetime(2024, 4, 24, 23, 53, 18, 304000, tzinfo=tzlocal()), 'pullStoppedAt': datetime.datetime(2024, 4, 24, 23, 53, 44, 363000, tzinfo=tzlocal()), 'startedAt': datetime.datetime(2024, 4, 24, 23, 53, 48, 814000, tzinfo=tzlocal()), 'startedBy': 'airflow', 'stopCode': 'EssentialContainerExited', 'stoppedAt': datetime.datetime(2024, 4, 25, 0, 11, 11, 387000, tzinfo=tzlocal()), 'stoppedReason': 'Essential container in task exited', 'stoppingAt': datetime.datetime(2024, 4, 25, 0, 10, 58, 220000, tzinfo=tzlocal()), 'tags': [], 'taskArn': 'arn:aws:ecs:us-west-2:777968769372:task/rikolti-ecs-cluster/ab29a84203c94508bc12408f8f689496', 'taskDefinitionArn': 'arn:aws:ecs:us-west-2:777968769372:task-definition/rikolti-content_harvester-task-definition:6', 'version': 6, 'ephemeralStorage': {'sizeInGiB': 20}}], 'failures': [], 'ResponseMetadata': {'RequestId': '2ecdc915-b8c8-409e-b5bf-0828fbf63213', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '2ecdc915-b8c8-409e-b5bf-0828fbf63213', 'content-type': 'application/x-amz-json-1.1', 'content-length': '3077', 'date': 'Thu, 25 Apr 2024 00:11:37 GMT'}, 'RetryAttempts': 0}}
[2024-04-25, 00:11:37 UTC] {{taskinstance.py:1824}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/dags/rikolti/dags/shared_tasks/content_harvest_operators.py", line 116, in execute
    return super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 476, in execute
    self._start_wait_check_task(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 743, in decorator_f
    return fun(self, *args, **kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 511, in _start_wait_check_task
    self._check_success_task()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 650, in _check_success_task
    raise AirflowException(
airflow.exceptions.AirflowException: This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 66, in harvest_record_content
    downloaded_md5 = download_content(request, http, media.tmp_filepath)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 203, in download_content
    f.write(block)
OSError: [Errno 28] No space left on device
Harvesting content for 33 records at 26711/vernacular_metadata_2024-04-24T22:02:32/mapped_metadata_2024-04-24T22:02:49/data/r-p0.jsonl
WARNING: no thumbnail found for ['sound']record 275428b8-6260-4fb8-93f7-0f431e70b59d in page 26711/vernacular_metadata_2024-04-24T22:02:32/mapped_metadata_2024-04-24T22:02:49/data/r-p0.jsonl
Used ffmpeg to convert /tmp/AS081-054-U.mp4 to /tmp/AS081-054-U.png
Used ffmpeg to convert /tmp/AS081-057-U.mp4 to /tmp/AS081-057-U.png
Used ffmpeg to convert /tmp/AS-081-128-A.mp4 to /tmp/AS-081-128-A.png
Used ffmpeg to convert /tmp/AS-081-137-A.mp4 to /tmp/AS-081-137-A.png
Used ffmpeg to convert /tmp/AS081-185-U.mp4 to /tmp/AS081-185-U.png
Used ffmpeg to convert /tmp/AS081-189-U.mp4 to /tmp/AS081-189-U.png
Used ffmpeg to convert /tmp/AS081-195-U.mp4 to /tmp/AS081-195-U.png
Used ffmpeg to convert /tmp/AS081-197-U.mp4 to /tmp/AS081-197-U.png
Used ffmpeg to convert /tmp/AS081-200-U.mp4 to /tmp/AS081-200-U.png
Used ffmpeg to convert /tmp/AS081-202-U.mp4 to /tmp/AS081-202-U.png
Used ffmpeg to convert /tmp/AS081-204-U.mp4 to /tmp/AS081-204-U.png
Used ffmpeg to convert /tmp/AS081-217-U.mp4 to /tmp/AS081-217-U.png
Used ffmpeg to convert /tmp/AS081-218-U.mp4 to /tmp/AS081-218-U.png
Used ffmpeg to convert /tmp/AS081-227-U.mp4 to /tmp/AS081-227-U.png
Used ffmpeg to convert /tmp/AS081-243-U.mp4 to /tmp/AS081-243-U.png
Used ffmpeg to convert /tmp/AS081-251-U.mp4 to /tmp/AS081-251-U.png
Used ffmpeg to convert /tmp/AS081-282-U.mp4 to /tmp/AS081-282-U.png
Used ffmpeg to convert /tmp/AS081-285-U.mp4 to /tmp/AS081-285-U.png
Used ffmpeg to convert /tmp/AS081-290-U.mp4 to /tmp/AS081-290-U.png
Used ffmpeg to convert /tmp/AS081-298-U.mp4 to /tmp/AS081-298-U.png
Used ffmpeg to convert /tmp/AS081-331-U.mp4 to /tmp/AS081-331-U.png
Used ffmpeg to convert /tmp/AS081-393-U.mp4 to /tmp/AS081-393-U.png
Used ffmpeg to convert /tmp/AS081-396-U.mp4 to /tmp/AS081-396-U.png
Used ffmpeg to convert /tmp/AS081-398-U.mp4 to /tmp/AS081-398-U.png
Used ffmpeg to convert /tmp/AS081-409-U.mp4 to /tmp/AS081-409-U.png
Used ffmpeg to convert /tmp/AS081-416-U.mp4 to /tmp/AS081-416-U.png
Used ffmpeg to convert /tmp/AS081-424-U.mp4 to /tmp/AS081-424-U.png
ERROR: no thumbnail found for Nonerecord ac9c3d42-d465-4196-a5d5-c503afdc1f8d in page 26711/vernacular_metadata_2024-04-24T22:02:32/mapped_metadata_2024-04-24T22:02:49/data/r-p0.jsonl
Used ffmpeg to convert /tmp/AS-081-72-A.mp4 to /tmp/AS-081-72-A.png
[2024-04-25, 00:11:37 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=0, execution_date=20240424T220220, start_date=20240424T235303, end_date=20240425T001137
[2024-04-25, 00:11:37 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: 9efa3f46-8b05-5dbc-8062-61e52afcca10
[2024-04-25, 00:11:37 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 80348 for task content_harvesting.content_harvest (This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 66, in harvest_record_content
    downloaded_md5 = download_content(request, http, media.tmp_filepath)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 203, in download_content
    f.write(block)
OSError: [Errno 28] No space left on device
Harvesting content for 33 records at 26711/vernacular_metadata_2024-04-24T22:02:32/mapped_metadata_2024-04-24T22:02:49/data/r-p0.jsonl
WARNING: no thumbnail found for ['sound']record 275428b8-6260-4fb8-93f7-0f431e70b59d in page 26711/vernacular_metadata_2024-04-24T22:02:32/mapped_metadata_2024-04-24T22:02:49/data/r-p0.jsonl
Used ffmpeg to convert /tmp/AS081-054-U.mp4 to /tmp/AS081-054-U.png
Used ffmpeg to convert /tmp/AS081-057-U.mp4 to /tmp/AS081-057-U.png
Used ffmpeg to convert /tmp/AS-081-128-A.mp4 to /tmp/AS-081-128-A.png
Used ffmpeg to convert /tmp/AS-081-137-A.mp4 to /tmp/AS-081-137-A.png
Used ffmpeg to convert /tmp/AS081-185-U.mp4 to /tmp/AS081-185-U.png
Used ffmpeg to convert /tmp/AS081-189-U.mp4 to /tmp/AS081-189-U.png
Used ffmpeg to convert /tmp/AS081-195-U.mp4 to /tmp/AS081-195-U.png
Used ffmpeg to convert /tmp/AS081-197-U.mp4 to /tmp/AS081-197-U.png
Used ffmpeg to convert /tmp/AS081-200-U.mp4 to /tmp/AS081-200-U.png
Used ffmpeg to convert /tmp/AS081-202-U.mp4 to /tmp/AS081-202-U.png
Used ffmpeg to convert /tmp/AS081-204-U.mp4 to /tmp/AS081-204-U.png
Used ffmpeg to convert /tmp/AS081-217-U.mp4 to /tmp/AS081-217-U.png
Used ffmpeg to convert /tmp/AS081-218-U.mp4 to /tmp/AS081-218-U.png
Used ffmpeg to convert /tmp/AS081-227-U.mp4 to /tmp/AS081-227-U.png
Used ffmpeg to convert /tmp/AS081-243-U.mp4 to /tmp/AS081-243-U.png
Used ffmpeg to convert /tmp/AS081-251-U.mp4 to /tmp/AS081-251-U.png
Used ffmpeg to convert /tmp/AS081-282-U.mp4 to /tmp/AS081-282-U.png
Used ffmpeg to convert /tmp/AS081-285-U.mp4 to /tmp/AS081-285-U.png
Used ffmpeg to convert /tmp/AS081-290-U.mp4 to /tmp/AS081-290-U.png
Used ffmpeg to convert /tmp/AS081-298-U.mp4 to /tmp/AS081-298-U.png
Used ffmpeg to convert /tmp/AS081-331-U.mp4 to /tmp/AS081-331-U.png
Used ffmpeg to convert /tmp/AS081-393-U.mp4 to /tmp/AS081-393-U.png
Used ffmpeg to convert /tmp/AS081-396-U.mp4 to /tmp/AS081-396-U.png
Used ffmpeg to convert /tmp/AS081-398-U.mp4 to /tmp/AS081-398-U.png
Used ffmpeg to convert /tmp/AS081-409-U.mp4 to /tmp/AS081-409-U.png
Used ffmpeg to convert /tmp/AS081-416-U.mp4 to /tmp/AS081-416-U.png
Used ffmpeg to convert /tmp/AS081-424-U.mp4 to /tmp/AS081-424-U.png
ERROR: no thumbnail found for Nonerecord ac9c3d42-d465-4196-a5d5-c503afdc1f8d in page 26711/vernacular_metadata_2024-04-24T22:02:32/mapped_metadata_2024-04-24T22:02:49/data/r-p0.jsonl
Used ffmpeg to convert /tmp/AS-081-72-A.mp4 to /tmp/AS-081-72-A.png; 5467)
[2024-04-25, 00:11:37 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2024-04-25, 00:11:37 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check

```
## Mapped metadata for the error:
`{"calisphere-id": "ac9c3d42-d465-4196-a5d5-c503afdc1f8d", "campus_data": ["3::UC Irvine"], "campus_name": ["UC Irvine"], "campus_url": ["3"], "collection_data": ["26711::University Communications audio and video recordings (University of California, Irvine)"], "collection_name": ["University Communications audio and video recordings (University of California, Irvine)"], "collection_url": ["26711"], "fetcher_type": ["nuxeo"], "id": "ac9c3d42-d465-4196-a5d5-c503afdc1f8d", "is_shown_at": "https://calisphere.org/item/ac9c3d42-d465-4196-a5d5-c503afdc1f8d", "is_shown_by": {"url": "https://nuxeo.cdlib.org/nuxeo/nxfile/default/ac9c3d42-d465-4196-a5d5-c503afdc1f8d/file:content/AS-081-72-A.mov?changeToken=7-0", "mimetype": "video/quicktime", "filename": "AS-081-72-A.mov", "nuxeo_type": "CustomVideo"}, "item_count": 0, "mapper_type": ["nuxeo.nuxeo"], "media_source": {"url": "https://nuxeo.cdlib.org/nuxeo/nxfile/default/ac9c3d42-d465-4196-a5d5-c503afdc1f8d/file:content/AS-081-72-A.mov?changeToken=7-0", "mimetype": "video/quicktime", "filename": "AS-081-72-A.mov", "nuxeo_type": "CustomVideo"}, "repository_data": ["17::Libraries, University Archives::UC Irvine"], "repository_name": ["Libraries, University Archives"], "repository_url": ["17"], "rights": ["Please contact the contributing institution for more information regarding the copyright status of this object."], "sort_collection_data": ["university communications audio and video recordings university of california irvine::University Communications audio and video recordings (University of California, Irvine)::26711"], "sort_title": "as08172amov", "thumbnail_source": {"url": "https://nuxeo.cdlib.org/nuxeo/nxfile/default/ac9c3d42-d465-4196-a5d5-c503afdc1f8d/file:content/AS-081-72-A.mov?changeToken=7-0", "mimetype": "video/quicktime", "filename": "AS-081-72-A.mov", "nuxeo_type": "CustomVideo"}, "title": ["AS-081-72-A.mov"], "url_item": "https://calisphere.org/item/ac9c3d42-d465-4196-a5d5-c503afdc1f8d"}, 
`

## Mapped metadata for the warning:
`[{"calisphere-id": "275428b8-6260-4fb8-93f7-0f431e70b59d", "campus_data": ["3::UC Irvine"], "campus_name": ["UC Irvine"], "campus_url": ["3"], "collection_data": ["26711::University Communications audio and video recordings (University of California, Irvine)"], "collection_name": ["University Communications audio and video recordings (University of California, Irvine)"], "collection_url": ["26711"], "creator": ["University of California, Irvine"], "date": ["19 June 1998"], "description": ["Conservation History: Digitized 2015 by DUE Media Services at UC Irvine", "Scope/Content: Chancellor Wilkening’s remarks begin at 00:03:55 and end at 00:15:58.", "Scope/Content: Poor sound quality in the second half of the audio recording."], "extent": ["00:57:46"], "fetcher_type": ["nuxeo"], "format": ["m4a"], "id": "ark:/81235/d8f26x", "identifier": ["ark:/81235/d8f26x", "AS081-345-U.m4a", "AS-081-345"], "is_shown_at": "https://calisphere.org/item/275428b8-6260-4fb8-93f7-0f431e70b59d", "item_count": 0, "language": ["English", "eng"], "mapper_type": ["nuxeo.nuxeo"], "media_source": {"url": "https://nuxeo.cdlib.org/nuxeo/nxfile/default/275428b8-6260-4fb8-93f7-0f431e70b59d/file:content/AS081-346-U.m4a", "mimetype": "audio/aac", "filename": "AS081-346-U.m4a", "nuxeo_type": "CustomAudio"}, "repository_data": ["17::Libraries, University Archives::UC Irvine"], "repository_name": ["Libraries, University Archives"], "repository_url": ["17"], "rights": ["Copyrighted", "This material is provided for private study, scholarship, or research. Property rights reside with the University of California. Copyrights are generally retained by the creators of the records and their heirs, unless transferred to the University of California. It is the responsibility of the researcher to determine who holds the copyright and pursue the copyright owner or his or her heir for permission to publish where the UC Regents do not hold the copyright. For information on use, copyright, and attribution, please visit: https://special.lib.uci.edu/use-copyright-and-attribution"], "sort_collection_data": ["university communications audio and video recordings university of california irvine::University Communications audio and video recordings (University of California, Irvine)::26711"], "sort_title": "uc regents meeting chancellor laurel l wilkenings remarks", "subject": ["University of California, Irvine"], "thumbnail_source": {}, "title": ["UC Regents Meeting, Chancellor Laurel L. Wilkening's Remarks"], "type": ["sound"], "url_item": "https://calisphere.org/item/275428b8-6260-4fb8-93f7-0f431e70b59d"}, `

**Comment by christinklez** [comment]
It does look like the legacy harvester previously supported MOV files, as in this collection example:
- Calisphere: https://calisphere.org/collections/27
- Nuxeo project folder: https://nuxeo.cdlib.org/nuxeo/nxdoc/default/5b191b9e-8135-4b46-ad57-340e7ea03bfc/view_documents

Clicking to view the item record pages results in a 500 error.
- Stage: https://calisphere-stage.cdlib.org/collections/27

**Comment by barbarahui** [comment]
The "no space left on device" error is an actual problem and is happening because this video file is huge and the ECS worker doesn't have enough space to process it (5GB)

The warning message should be resolved now with the recent fix for quicktime movie files. However, is it OK that `ucldc_schema:type` is `None` for this object? I forget if that's a required metadata field or not.

**Comment by christinklez** [comment]
Messaged UCI about the collection 26711 -- the 5 GB file may not be intended for publication. Stay tuned!

**Comment by christinklez** [comment]
The supersized 5GB file should no longer be an issue, so I'm going to close this out.
