### ISSUE TITLE
[bug] content harvest `PIL.UnidentifiedImageError` issues for `oai.omeka` collections (errors trying to thumbnail pdf, mp3, and video files)

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#899]
mapper: `oai.omeka`

## collection 26724
- Run ID: manual__2024-04-26T01:03:13+00:00
- content harvest, mapped page 2 & 6
- link to gridview: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-04-26T01%3A03%3A13%2B00%3A00&num_runs=365&task_id=content_harvesting.content_harvest&tab=mapped_tasks
   - from mapped page 2: 
      - permalink to the log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-26T01%3A03%3A13%2B00%3A00&map_index=2
      - record on -test: https://calisphere-test.cdlib.org/item/dfddd2325ace0a519264b83c59bcca2a/ (broken thumbnail for the pdf)
   - from mapped page 6: 
      - permalink to the log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-26T01%3A03%3A13%2B00%3A00&map_index=6
      - record on -test: https://calisphere-test.cdlib.org/item/769c1d0a57f8cd49577ef012f3e994ec/ (audio icon on -test; source record is audio)

**From mapped page 2:**
```
Harvesting content for 50 records at 26724/vernacular_metadata_2024-04-26T01:03:24/mapped_metadata_2024-04-26T01:04:36/data/5.jsonl
[2024-04-26, 01:07:41 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=2, execution_date=20240426T010313, start_date=20240426T010509, end_date=20240426T010741
[2024-04-26, 01:07:41 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: d321fd60-032e-5f86-930a-a3c503b3dcae
[2024-04-26, 01:07:41 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 86798 for task content_harvesting.content_harvest (This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
  File "/content_harvester/by_record.py", line 150, in get_dimensions
    return Image.open(filepath).size
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/b8b066f579b244fbf3f429114a2e034d.pdf'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 112, in harvest_record_content
    dimensions = get_dimensions(thumbnail.tmp_filepath, record['calisphere-id'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 152, in get_dimensions
    raise Exception(
Exception: PIL.UnidentifiedImageError for calisphere-id oai:annahalprindigitalarchive.omeka.net:503: cannot identify image file '/tmp/b8b066f579b244fbf3f429114a2e034d.pdf'
Harvesting content for 50 records at 26724/vernacular_metadata_2024-04-26T01:03:24/mapped_metadata_2024-04-26T01:04:36/data/4.jsonl
Harvested 50 thumbnail records
50/50 described a thumbnail source
Source Thumbnail Mimetypes: Counter({None: 50})
Destination Thumbnail Mimetypes: Counter({'image/jpeg': 50})
```

**From mapped page 6:**
```
Harvesting content for 50 records at 26724/vernacular_metadata_2024-04-26T01:03:24/mapped_metadata_2024-04-26T01:04:36/data/13.jsonl
[2024-04-26, 01:07:36 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=6, execution_date=20240426T010313, start_date=20240426T010504, end_date=20240426T010736
[2024-04-26, 01:07:36 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: 9ed46b1c-f32d-5f62-8761-35b9f3b55a6c
[2024-04-26, 01:07:36 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 86775 for task content_harvesting.content_harvest (This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
  File "/content_harvester/by_record.py", line 150, in get_dimensions
    return Image.open(filepath).size
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/1be92010450991a8170c692c0f2c6836.mp3'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 112, in harvest_record_content
    dimensions = get_dimensions(thumbnail.tmp_filepath, record['calisphere-id'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 152, in get_dimensions
    raise Exception(
Exception: PIL.UnidentifiedImageError for calisphere-id oai:annahalprindigitalarchive.omeka.net:678: cannot identify image file '/tmp/1be92010450991a8170c692c0f2c6836.mp3'
```

## collection 26725
- Run ID: manual__2024-04-26T01:03:08+00:00
- content harvest, mapped task: page 8
- record on -test: https://calisphere-test.cdlib.org/item/75849f3c4a6f721dca3d2c169626d3a2/ (broken thumbnail for the pdf)
- Gridview: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-04-26T01%3A03%3A08%2B00%3A00&num_runs=365&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=8
- Permalink to the log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-26T01%3A03%3A08%2B00%3A00&map_index=8
```
Harvesting content for 36 records at 26725/vernacular_metadata_2024-04-26T01:03:20/mapped_metadata_2024-04-26T01:03:45/data/8.jsonl
[2024-04-26, 01:06:22 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=8, execution_date=20240426T010308, start_date=20240426T010420, end_date=20240426T010622
[2024-04-26, 01:06:22 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: 068a8c93-6744-5129-91e9-d236670a5fc6
[2024-04-26, 01:06:22 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 86702 for task content_harvesting.content_harvest (This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
  File "/content_harvester/by_record.py", line 150, in get_dimensions
    return Image.open(filepath).size
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/db2f643e01e47b6750263bb6e2eccae0.pdf'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 112, in harvest_record_content
    dimensions = get_dimensions(thumbnail.tmp_filepath, record['calisphere-id'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 152, in get_dimensions
    raise Exception(
Exception: PIL.UnidentifiedImageError for calisphere-id oai:christensenfamilycollection.omeka.net:443: cannot identify image file '/tmp/db2f643e01e47b6750263bb6e2eccae0.pdf'
Harvesting content for 36 records at 26725/vernacular_metadata_2024-04-26T01:03:20/mapped_metadata_2024-04-26T01:03:45/data/8.jsonl; 16243)
[2024-04-26, 01:06:22 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
```

## collection 27622
- Run ID: manual__2024-04-26T01:21:25+00:00
- Content harvest, mapped page 0
- record on -test: https://calisphere-test.cdlib.org/item/7beac90369420d127aacc8117e1bfad3/ (audio icon on -test, but source record is a video)
- Gridview: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-04-26T01%3A21%3A25%2B00%3A00&num_runs=365&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=0
- Permalink to the log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-26T01%3A21%3A25%2B00%3A00&map_index=0
```
Harvesting content for 30 records at 27622/vernacular_metadata_2024-04-26T01:21:37/mapped_metadata_2024-04-26T01:21:56/data/0.jsonl
[2024-04-26, 01:24:01 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=0, execution_date=20240426T012125, start_date=20240426T012229, end_date=20240426T012401
[2024-04-26, 01:24:01 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: 35b86b50-5679-585f-bc58-35f552088235
[2024-04-26, 01:24:02 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 86957 for task content_harvesting.content_harvest (This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
  File "/content_harvester/by_record.py", line 150, in get_dimensions
    return Image.open(filepath).size
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/5c80dbbca508a80851e85eab40b49ac0.jpg'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 112, in harvest_record_content
    dimensions = get_dimensions(thumbnail.tmp_filepath, record['calisphere-id'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 152, in get_dimensions
    raise Exception(
Exception: PIL.UnidentifiedImageError for calisphere-id oai:photographs.venturamuseum.org:2508: cannot identify image file '/tmp/5c80dbbca508a80851e85eab40b49ac0.jpg'
```
## collection 27623
- Run ID: manual__2024-04-26T01:21:23+00:00
- Content harvest, mapped page
- record on -test: https://calisphere-test.cdlib.org/item/4a66ce632e265420c1b344e86b733b9e/ (audio icon on -test, but source record is a video)
- Gridview: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-04-26T01%3A21%3A23%2B00%3A00&num_runs=365&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=0
- Permalink to the log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-26T01%3A21%3A23%2B00%3A00&map_index=0
```
Harvesting content for 7 records at 27623/vernacular_metadata_2024-04-26T01:21:34/mapped_metadata_2024-04-26T01:21:49/data/0.jsonl
[2024-04-26, 01:24:00 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=0, execution_date=20240426T012123, start_date=20240426T012228, end_date=20240426T012400
[2024-04-26, 01:24:00 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: d25bdcc3-016f-5e78-b6eb-8266051f9076
[2024-04-26, 01:24:00 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 86955 for task content_harvesting.content_harvest (This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
  File "/content_harvester/by_record.py", line 150, in get_dimensions
    return Image.open(filepath).size
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/4cb5fdfb7fc047cdd8b6c5ba78455020.jpg'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 112, in harvest_record_content
    dimensions = get_dimensions(thumbnail.tmp_filepath, record['calisphere-id'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 152, in get_dimensions
    raise Exception(
Exception: PIL.UnidentifiedImageError for calisphere-id oai:photographs.venturamuseum.org:2776: cannot identify image file '/tmp/4cb5fdfb7fc047cdd8b6c5ba78455020.jpg'
```
## collection 27667
- Run ID: manual__2024-04-26T01:21:13+00:00
- record on -test: https://calisphere-test.cdlib.org/item/85c2f467a8f05e5d74b29c498e50f8f1/ (audio icon on -test, source record is audio)
- Gridview: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-04-26T01%3A21%3A13%2B00%3A00&num_runs=365&task_id=content_harvesting.content_harvest&tab=mapped_tasks
- Permalink to the log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-26T01%3A21%3A13%2B00%3A00&map_index=0
```
Harvesting content for 3 records at 27667/vernacular_metadata_2024-04-26T01:21:25/mapped_metadata_2024-04-26T01:21:37/data/0.jsonl
[2024-04-26, 01:23:41 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=0, execution_date=20240426T012113, start_date=20240426T012209, end_date=20240426T012341
[2024-04-26, 01:23:41 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: c28014a6-9add-5131-9f5e-4a039e806fdb
[2024-04-26, 01:23:41 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 86914 for task content_harvesting.content_harvest (This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
  File "/content_harvester/by_record.py", line 150, in get_dimensions
    return Image.open(filepath).size
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/b4b546d2e6c2136e8e6c56e1b2df289f.jpg'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 112, in harvest_record_content
    dimensions = get_dimensions(thumbnail.tmp_filepath, record['calisphere-id'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 152, in get_dimensions
    raise Exception(
Exception: PIL.UnidentifiedImageError for calisphere-id oai:photographs.venturamuseum.org:2730: cannot identify image file '/tmp/b4b546d2e6c2136e8e6c56e1b2df289f.jpg'
```

## collection 27669
- Run ID: manual__2024-04-26T01:21:02+00:00
- record on -test: https://calisphere-test.cdlib.org/item/f70ee191c48c0e9279a41c15b9784fec/ (audio icon on -test, but the source record is a video)
- Gridview: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-04-26T01%3A21%3A02%2B00%3A00&num_runs=365&task_id=content_harvesting.content_harvest&tab=mapped_tasks
- Permalink to the log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-26T01%3A21%3A02%2B00%3A00&map_index=0
```
Harvesting content for 17 records at 27669/vernacular_metadata_2024-04-26T01:21:15/mapped_metadata_2024-04-26T01:21:27/data/0.jsonl
[2024-04-26, 01:23:33 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=0, execution_date=20240426T012102, start_date=20240426T012200, end_date=20240426T012333
[2024-04-26, 01:23:33 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: a1cb55f3-bbdd-5369-83db-0b56bf8858c3
[2024-04-26, 01:23:33 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 86897 for task content_harvesting.content_harvest (This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
  File "/content_harvester/by_record.py", line 150, in get_dimensions
    return Image.open(filepath).size
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/7e9f235f6a9144c04f0089e062881bff.jpg'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 112, in harvest_record_content
    dimensions = get_dimensions(thumbnail.tmp_filepath, record['calisphere-id'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 152, in get_dimensions
    raise Exception(
Exception: PIL.UnidentifiedImageError for calisphere-id oai:photographs.venturamuseum.org:2622: cannot identify image file '/tmp/7e9f235f6a9144c04f0089e062881bff.jpg'
```
## collection 27121
- Run ID: manual__2024-04-26T01:33:02+00:00
- record on -test: https://calisphere-test.cdlib.org/item/090de49950b792aeeb796bdcbc6620c7/ (pdf icon; source record is a PDF)
- Gridview: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-04-26T01%3A33%3A02%2B00%3A00&num_runs=365&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=0
- Permalink to the log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-26T01%3A33%3A02%2B00%3A00&map_index=0
```
Harvesting content for 50 records at 27121/vernacular_metadata_2024-04-26T01:33:14/mapped_metadata_2024-04-26T01:33:26/data/0.jsonl
[2024-04-26, 01:35:23 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=0, execution_date=20240426T013302, start_date=20240426T013351, end_date=20240426T013523
[2024-04-26, 01:35:23 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: f532ed43-28da-54b7-9097-b3e62fc1df9f
[2024-04-26, 01:35:23 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 87139 for task content_harvesting.content_harvest (This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
  File "/content_harvester/by_record.py", line 150, in get_dimensions
    return Image.open(filepath).size
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/3d3f5e3138c5918008132ebeacce37df.pdf'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 112, in harvest_record_content
    dimensions = get_dimensions(thumbnail.tmp_filepath, record['calisphere-id'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 152, in get_dimensions
    raise Exception(
Exception: PIL.UnidentifiedImageError for calisphere-id oai:welgadigitalarchive.omeka.net:53: cannot identify image file '/tmp/3d3f5e3138c5918008132ebeacce37df.pdf'
```

## collection 27122
- Run ID: manual__2024-04-26T01:32:59+00:00
- record on -test: https://calisphere-test.cdlib.org/item/d4c6185b45b934e9c7569cfc4ea4a20f/ (PDF icon; source records are PDFs)
- Gridview: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-04-26T01%3A32%3A59%2B00%3A00&num_runs=365&task_id=content_harvesting.content_harvest&tab=mapped_tasks&map_index=0
- Permalink to the log: https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-04-26T01%3A32%3A59%2B00%3A00&map_index=0
```
Harvesting content for 47 records at 27122/vernacular_metadata_2024-04-26T01:33:10/mapped_metadata_2024-04-26T01:33:22/data/0.jsonl
[2024-04-26, 01:35:14 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=0, execution_date=20240426T013259, start_date=20240426T013342, end_date=20240426T013514
[2024-04-26, 01:35:14 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: b4541956-1feb-56eb-9e3a-47f318f99e07
[2024-04-26, 01:35:14 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 87136 for task content_harvesting.content_harvest (This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
  File "/content_harvester/by_record.py", line 150, in get_dimensions
    return Image.open(filepath).size
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/30ec0145bbe99f50aa711ea33e505cc9.pdf'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 112, in harvest_record_content
    dimensions = get_dimensions(thumbnail.tmp_filepath, record['calisphere-id'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 152, in get_dimensions
    raise Exception(
Exception: PIL.UnidentifiedImageError for calisphere-id oai:welgadigitalarchive.omeka.net:18: cannot identify image file '/tmp/30ec0145bbe99f50aa711ea33e505cc9.pdf'
```

**Comment by barbarahui** [comment]
It looks like all of these objects have thumbnails that are not actually images, so the content harvester throws an error when trying to get the dimensions. I think the legacy harvester also throws an error when it encounters non-image thumbnails?

**Comment by christinklez** [comment]
Thanks! I think it's fine for these to not have thumbnails (and instead have an icon instead), but it seems that the harvester is error'ing out and stopping.

**Comment by barbarahui** [comment]
Gotcha. It sounds like we need to update the content harvester to recognize when a thumbnail is not actually an image. If this is the case, then that object should not have a `thumbnail`. And then the frontend needs to handle this gracefully too. Apparently the legacy harvester and frontend code are handling this, but rikolti and the new frontend code are not.

**Comment by christinklez** [comment]
Question: Is the `omeka` mapper trying to fish out a thumbnail for records that don't have a thumbnail? @amywieliczka will look into the `omeka` mapper logic.

It seems these records aren't expected to have thumbnails and should have a type icon instead.

**Comment by christinklez** [comment]
All of these harvested through! And they look great, for the most part!

The only exception is this record:
https://calisphere-stage.cdlib.org/item/4a66ce632e265420c1b344e86b733b9e/
which strangely has a type icon & a broken thumbnail.

(Other video records with a play button look okay.)

**Comment by barbarahui** [comment]
The is_shown_by link we got for that item is broken: https://photographs.venturamuseum.org/files/thumbnails/458cc920c7b9387798d79e4f2c6589fa.jpg

The content harvester shouldn't have created a thumbnail for it though...

**Comment by barbarahui** [comment]
Actually, the content harvester believes that this is a jpeg and downloads what it finds at the url, which in this case is an html page. Then the Calisphere frontend thumbnail server doesn't know what to do with it. I think we need to add some logic to the content harvester to check whether or not people are actually pointing us to an image?

**Comment by barbarahui** [comment]
Actually I think we need to change the logic. If getting the dimensions fails, then I think it's a good indicator that this file is not an image, in which case we should not upload it to S3.

**Comment by christinklez** [comment]
Ah! Interesting, that would also help with:
- the UCLA images that have cut off the isShownBy URLs: https://github.com/ucldc/rikolti/issues/921
- these Quartex images too: https://github.com/ucldc/rikolti/issues/922

(they have dimensions errors as well)

**Comment by barbarahui** [comment]
I'm not sure what the frontend does if a non-audio object is missing a thumbnail. I think it might break things?

**Comment by barbarahui** [comment]
Actually, it looks like it just displays a type icon if we couldn't get a thumbnail. That seems like the desired behavior?

**Comment by christinklez** [comment]
That is super ideal!

**Comment by barbarahui** [comment]
PR: https://github.com/ucldc/rikolti/pull/937
This changes the thumbnail creation logic so that we only create a thumbnail if get_dimensions() succeeds.

**Comment by barbarahui** [comment]
@christinklez Can you try rerunning the harvest for `27623` again? I think you just need to rerun the `content_harvest`, `merge_any_child_records`, and `create_stage_index` tasks.
