### ISSUE TITLE
[bug?] `oai.samvera` content harvesting error `botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the RunTask operation: Container Overrides length must be at most 8192` - registry ID 27768

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#920]
The content harvesting task instantly fails for all map index pages when the content harvesting task begins to run. Is this a Rikolti issue or a Samvera (UCLA-side) issue?

- oai.samvera
- Registry ID: 27768
- Run ID: manual__2024-05-03T23:44:52+00:00
- [permalink to airflow gridview](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?num_runs=365&base_date=2024-05-03T23%3A44%3A52%2B00%3A00&dag_run_id=manual__2024-05-03T23%3A44%3A52%2B00%3A00&task_id=content_harvesting.content_harvest)
- permalink to [map index 0 log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=content_harvesting.content_harvest&execution_date=2024-05-03T23%3A44%3A52%2B00%3A00&map_index=0)

```
[2024-05-07, 20:12:17 UTC] {{taskinstance.py:1824}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/dags/rikolti/dags/shared_tasks/content_harvest_operators.py", line 116, in execute
    return super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 476, in execute
    self._start_wait_check_task(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 743, in decorator_f
    return fun(self, *args, **kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 493, in _start_wait_check_task
    self._start_task(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 543, in _start_task
    response = self.client.run_task(**run_opts)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/botocore/client.py", line 964, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the RunTask operation: Container Overrides length must be at most 8192
[2024-05-07, 20:12:17 UTC] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=0, execution_date=20240503T234452, start_date=20240507T201216, end_date=20240507T201217
[2024-05-07, 20:12:17 UTC] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: acbc6eb1-d7f0-5997-9e1b-30055a913390
[2024-05-07, 20:12:17 UTC] {{standard_task_runner.py:104}} ERROR - Failed to execute job 116216 for task content_harvesting.content_harvest (An error occurred (InvalidParameterException) when calling the RunTask operation: Container Overrides length must be at most 8192; 1736)
[2024-05-07, 20:12:17 UTC] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2024-05-07, 20:12:18 UTC] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by barbarahui** [comment]
This is a rikolti issue.

**Comment by barbarahui** [comment]
We are fetching 7330 pages of metadata from this URL: https://digital.library.ucla.edu/catalog/oai?verb=ListIdentifiers&metadataPrefix=oai_dpla&set=member_of_collection_ids_ssim:k13t1n-89112

**Comment by christinklez** [comment]
Data entry issue. The incorrect endpoint was placed in the collection registry, and the harvest job attempted to harvest over 188k records. Once the endpoint was corrected, the harvest job picked up the desired 5 objects: https://calisphere-stage.cdlib.org/collections/27768/
