### ISSUE TITLE
"content_harvest" fails for entire collection `26762`; 1 item (?) has invalid or corrupted image file

### ISSUE THREAD

**Issue by aturner** [ucldc/rikolti#932]
**Issue:** CSU Chico's collection `26762` (CONTENTdm) fails at the "content_harvest" point; from the logs, it looks like it is tripping up on 1 item (?), an image object which appears to have an invalid or corrupted image file. Legacy harvester somehow took the object in, and we're displaying a missing thumbnail. Can we exclude / skip over this object?

**Collection** ID: 26762

**Rikolti mapper type:** ETL

**Airflow Run ID:** manual__2024-05-09T22:06:14+00:00

**Airflow log:** https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?base_date=manual__2024-05-09T22%3A06%3A14%2B00%3A00&num_runs=365&dag_run_id=manual__2024-05-09T22%3A06%3A14%2B00%3A00

**Item:**

- **CSphere prod view**: https://calisphere.org/item/98c5a06b8ad73576bc52f54c7dbf492e/
- **CONTENTdm local view**: http://archives.csuchico.edu/digital/collection/coll11/id/17719
- **Solr**: https://harvest-stg.cdlib.org/solr/dc-collection/select?q=coll11%2F17719&wt=json&indent=true
- **CouchDB ID**: 26762--oai:archives.csuchico.edu:coll11/1771
- **IsShownBy**: http://archives.csuchico.edu/utils/getthumbnail/collection/coll11/id/17719

==

```
[2024-05-09, 15:15:17 PDT] {{taskinstance.py:1824}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/dags/rikolti/dags/shared_tasks/content_harvest_operators.py", line 116, in execute
    return super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 476, in execute
    self._start_wait_check_task(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 743, in decorator_f
    return fun(self, *args, **kwargs)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 511, in _start_wait_check_task
    self._check_success_task()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/providers/amazon/aws/operators/ecs.py", line 650, in _check_success_task
    raise AirflowException(
airflow.exceptions.AirflowException: This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
  File "/content_harvester/by_record.py", line 153, in get_dimensions
    return Image.open(filepath).size
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/11683c25ed8b744e440595fd35262ddf'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 113, in harvest_record_content
    dimensions = get_dimensions(thumbnail.tmp_filepath, record['calisphere-id'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 155, in get_dimensions
    raise Exception(
Exception: PIL.UnidentifiedImageError for calisphere-id oai:archives.csuchico.edu:coll11/17719: cannot identify image file '/tmp/11683c25ed8b744e440595fd35262ddf'
Harvesting content for 100 records at 26762/vernacular_metadata_2024-05-09T22:06:25/mapped_metadata_2024-05-09T22:07:22/data/135.jsonl
Harvested 100 thumbnail records
100/100 described a thumbnail source
Source Thumbnail Mimetypes: Counter({None: 100})
Destination Thumbnail Mimetypes: Counter({'image/jpeg': 100})
Harvesting content for 100 records at 26762/vernacular_metadata_2024-05-09T22:06:25/mapped_metadata_2024-05-09T22:07:22/data/136.jsonl
[2024-05-09, 15:15:17 PDT] {{taskinstance.py:1345}} INFO - Marking task as FAILED. dag_id=harvest_collection, task_id=content_harvesting.content_harvest, map_index=27, execution_date=20240509T220614, start_date=20240509T221314, end_date=20240509T221517
[2024-05-09, 15:15:17 PDT] {{logging_mixin.py:150}} INFO - Message sent to SNS with Message ID: 7b431d36-f024-5728-ac7c-4381bd11e2d8
[2024-05-09, 15:15:17 PDT] {{standard_task_runner.py:104}} ERROR - Failed to execute job 129133 for task content_harvesting.content_harvest (This task is not in success state - last 100 logs from Cloudwatch:
Traceback (most recent call last):
  File "/content_harvester/by_record.py", line 153, in get_dimensions
    return Image.open(filepath).size
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/11683c25ed8b744e440595fd35262ddf'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/content_harvester/by_page.py", line 98, in <module>
    print_value.append(harvest_page_content(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_page.py", line 31, in harvest_page_content
    record_with_content = harvest_record_content(
                          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 113, in harvest_record_content
    dimensions = get_dimensions(thumbnail.tmp_filepath, record['calisphere-id'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content_harvester/by_record.py", line 155, in get_dimensions
    raise Exception(
Exception: PIL.UnidentifiedImageError for calisphere-id oai:archives.csuchico.edu:coll11/17719: cannot identify image file '/tmp/11683c25ed8b744e440595fd35262ddf'
Harvesting content for 100 records at 26762/vernacular_metadata_2024-05-09T22:06:25/mapped_metadata_2024-05-09T22:07:22/data/135.jsonl
Harvested 100 thumbnail records
100/100 described a thumbnail source
Source Thumbnail Mimetypes: Counter({None: 100})
Destination Thumbnail Mimetypes: Counter({'image/jpeg': 100})
Harvesting content for 100 records at 26762/vernacular_metadata_2024-05-09T22:06:25/mapped_metadata_2024-05-09T22:07:22/data/136.jsonl; 213)
[2024-05-09, 15:15:17 PDT] {{local_task_job_runner.py:225}} INFO - Task exited with return code 1
[2024-05-09, 15:15:17 PDT] {{taskinstance.py:2653}} INFO - 0 downstream tasks scheduled from follow-on schedule check
```

**Comment by barbarahui** [comment]
I think that once we pull in the the PR for issue 899, the content harvester will just print a warning and we won't have a thumbnail: https://github.com/ucldc/rikolti/pull/917

**Comment by barbarahui** [comment]
@aturner I went ahead and merged that PR into main. Can you try re-running the content harvest step for the one failed mapped task?

**Comment by aturner** [comment]
Thanks, Barbara -- re-running that step now (observing a similar issue with collection 26203, https://github.com/ucldc/rikolti/issues/933 -- will also re-run the step for that one, too!)

**Comment by barbarahui** [comment]
@aturner You should be able to just clear and rerun the tasks that failed, btw. No need to rerun the tasks that succeeded!

**Comment by aturner** [comment]
That did the trick -- success!!! THANKS @barbarahui !!!

**Comment by aturner** [comment]
Resolved with PR for issue 899
