### ISSUE TITLE
[bug?] `AttributeError: 'NoneType' object has no attribute 'findall'` for one UCLA Samvera collection

### ISSUE THREAD

**Issue by christinklez** [ucldc/rikolti#979]
Question: Is this an OAI issue or a Rikolti issue?

**Registry ID: 28191**
- OAI: https://digital.library.ucla.edu/catalog/oai?verb=ListRecords&metadataPrefix=oai_dpla&set=member_of_collection_ids_ssim:gvb0j200zz-89112
- Permalink to [gridview](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/dags/harvest_collection/grid?dag_run_id=manual__2024-05-31T17%3A38%3A35%2B00%3A00&base_date=2024-05-31T17%3A38%3A35%2B00%3A00&task_id=fetching.fetch_collection&tab=logs)
- Permalink to [fetch task error log](https://7a8067cb-3b99-477e-a883-7e311175a9b4.c3.us-west-2.airflow.amazonaws.com/log?dag_id=harvest_collection&task_id=fetching.fetch_collection&execution_date=2024-05-31T17%3A38%3A35%2B00%3A00)

```
[2024-05-31, 17:38:52 UTC] {{taskinstance.py:1824}} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 220, in execute
    return_value = super().execute(context)
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/rikolti/dags/shared_tasks/fetching_tasks.py", line 37, in fetch_collection_task
    fetched_collection = fetch_collection(collection, vernacular_version)
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/lambda_function.py", line 92, in fetch_collection
    page_status = fetcher.fetch_page()
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/fetchers/Fetcher.py", line 77, in fetch_page
    record_count = self.check_page(response)
  File "/usr/local/airflow/dags/rikolti/metadata_fetcher/fetchers/oai_fetcher.py", line 72, in check_page
    'oai2:ListRecords', NAMESPACE).findall('oai2:record', NAMESPACE)
AttributeError: 'NoneType' object has no attribute 'findall'
```

**Comment by barbarahui** [comment]
The `harvest_extra_metadata` field value in the registry looks like it has extra spaces in it:

`metadataPrefix=oai_dpla&set=	member_of_collection_ids_ssim:gvb0j200zz-89112`

**Comment by christinklez** [comment]
Thank you!

Updated from:
`metadataPrefix=oai_dpla&set=	member_of_collection_ids_ssim:gvb0j200zz-89112`

to:
`metadataPrefix=oai_dpla&set=member_of_collection_ids_ssim:gvb0j200zz-89112`
